# -*- coding: utf-8 -*-
"""v1.6.0 批次 A-de：德语核心翻译（非事件键）。"""
import io, json, collections

DE = collections.OrderedDict()
def t(**kw):
    DE.update(kw)

t(**{
 'tab_economy_name': 'Klassische Ökonomie',
 'tab_economy_desc': 'Klassische Ökonomie-Tab',
 'economy_toggle': 'Wirtschaftspanel',
 'economy_toggle_description': 'Wirtschaftsübersicht ein-/ausblenden',
 'economy_intervene': 'Intervention',
 'economy_intervene_description': 'Länderliste für Aufwiegelung/Unterdrückung öffnen',
 'economy_collect': 'Jetzt erfassen',
 'economy_collect_description': 'Datenerfassung und Neuberechnung manuell ausführen',
 'economy_clear': 'Verlauf löschen',
 'economy_clear_description': 'Verlaufs-Snapshots löschen',
 'economy_rich': 'Reichstenliste',
 'economy_rich_description': 'Top 10 der vermögendsten Einwohner',
 'economy_events': 'Ereignisse',
 'economy_events_description': 'Ereignisfeed ein-/ausblenden',
 'economy_cycle_phase': 'Zyklusphase',
 'economy_cycle_phase_description': 'Boom→Rezession→Depression→Erholung manuell schalten',
 'col_avg': 'Ø', 'col_gini': 'Gini', 'stat_bubble': 'Blase',
 'overview_cycle': 'Zyklus #{0}',
 'overview_kingdoms': 'Königreichs-Ranking',
 'overview_no_kingdom': 'Keine Königreiche',
 'unrest_state_title': 'Unruhe-Status',
 'overview_no_unrest': 'Ruhig',
 'chart_title_dyn': 'GDP-Trend Top{0} (Jahr {1}, {2} Zyklen)',
 'chart_no_data': 'Keine Daten',
 'chart_legend_hint': 'Legende: nach Königreich',
 'chart_summary': 'Max {0} → Aktuell {1}',
 'gini_chart_title': 'Gini-Trend (Jahr {0}, {1} Zyklen)',
 'gini_legend_phase': 'Farbband = Zyklusphase',
 'gini_legend_danger': 'Gefahrenzone',
 'gini_legend_health': 'Gesunde Zone',
 'settling_marker': 'Abrechnung…',
 'settling_hint': 'Jahresabrechnung läuft: Erfassung & Phasenwechsel deaktiviert',
 'event_title': 'Ereignisse',
 'event_subtitle': 'Jahr {0} · {1} Ereignisse',
 'events_none': 'Noch keine Ereignisse',
 'events_major': '── Große Ereignisse ──',
 'events_recent': '── Letzte Ereignisse ──',
 'events_filter_all': 'Alle', 'events_filter_decision': 'Entscheidungen',
 'events_filter_politics': 'Staaten & Kriege', 'events_filter_economy': 'Wirtschaft',
 'events_fold_year': 'Jahr {0} ({1} Einträge) ▸',
 'events_year_hdr': '── Jahr {0} ──',
 'events_row': 'J{0}{1} {2}',
 'rich_title': 'Reichstenliste',
 'rich_subtitle': 'Jahr {0} · {1} zivilisiert',
 'rich_none': 'Niemand erfüllt die Kriterien',
 'rich_row': '{0}. {1}: {2}G',
})

t(**{
 'cabinet_title': 'Kabinett',
 'cabinet_tab_finance': 'Finanzen', 'cabinet_tab_policy': 'Politik',
 'cabinet_tab_decree': 'Dekrete & Bau', 'cabinet_tab_diplomacy': 'Diplomatie',
 'cabinet_tab_codex': 'Kodex', 'cabinet_tab_bank': 'Bank & Handel',
 'cabinet_disabled': 'Zentralbankier-Modus ist deaktiviert (in den Einstellungen aktivieren)',
 'cabinet_no_nation': 'Kein Land gewählt: unten ein Land wählen, um das Kabinett zu öffnen',
 'cabinet_claim_hint': 'Bei Wahl werden 20% der Stadtkassen als Schatzkammer überwiesen',
 'cabinet_claim_row': '{0} (GDP {1}) übernehmen',
 'picker_empty': 'Keine Kandidaten',
 'cabinet_nation': 'Königsschatz von {0}',
 'cabinet_ruler': 'Regierend: {0}',
 'cabinet_treasury': 'Schatzkammer: {0}',
 'cabinet_flow': 'Letztes Jahr Einnahmen {0} | Ausgaben {1}',
 'cabinet_switch_cooldown': 'Länderwechsel-Abklingzeit: noch {0} Jahre',
 'cabinet_policy_cost': 'Jahr: klein {0} | mittel {1} | groß {2}',
 'cabinet_policy_active': '{0} · Stufe {1}',
 'cabinet_enable': 'Aktivieren', 'cabinet_upgrade': 'Aufstufen', 'cabinet_disable': 'Beenden',
 'cabinet_decree_cooling': '{0} (Abklingzeit)',
 'cabinet_execute': 'Ausführen',
 'cabinet_build_title': 'Bauen (auf der Karte platzieren)',
 'cabinet_build_market': 'Markt', 'cabinet_build_granary': 'Kornspeicher',
 'cabinet_law_nation': 'Kodex von {0}', 'cabinet_law_style': 'Nationalcharakter: {0}',
 'cabinet_law_effect_title': 'Aktuelle Gesamtwirkung', 'cabinet_law_policy_hdr': 'Politiken',
 'law_cat_economy': 'Wirtschaftsgesetze', 'law_cat_welfare': 'Sozialgesetze',
 'law_cat_military': 'Militärgesetze', 'law_cat_judicial': 'Justiz & Verwaltung',
 'law_cat_culture': 'Kultur & Religion',
 'law_lv0': 'Keine', 'law_lv1': 'Leicht', 'law_lv2': 'Mittel', 'law_lv3': 'Schwer', 'law_lv4': 'Extrem',
 'law_pol_lv0': 'Keine', 'law_pol_lv1': 'Wenig', 'law_pol_lv2': 'Viel',
 'law_eff_production': 'Produktion', 'law_eff_tax': 'Steuern', 'law_eff_price': 'Preise',
 'law_eff_consume': 'Konsum', 'law_eff_disaster': 'Katastrophen', 'law_eff_build': 'Baukosten',
 'law_eff_wage': 'Löhne', 'law_eff_unrest': 'Unruhe', 'law_eff_happiness': 'Zufriedenheit',
 'law_eff_military': 'Militär', 'law_eff_birth': 'Geburten',
 'cabinet_dip_back': 'Zurück', 'cabinet_dip_actions': 'Diplomatische Aktionen',
 'cabinet_dip_war': 'Krieg erklären', 'cabinet_dip_peace': 'Frieden',
 'cabinet_dip_alliance': 'Bündnis', 'cabinet_dip_gift': 'Geschenk (500G)',
 'cabinet_dip_pact': 'Wirtschaftspakt', 'cabinet_dip_pact_on': 'Wirtschaftspakt · Stufe {0}',
 'cabinet_dip_list_row': '{0} (GDP {1}) Bezieh. {2} Wohlw. {3}',
 'cabinet_dip_stat_relation': 'Beziehungen {0} | Wohlwollen {1}',
 'cabinet_dip_stat_style': 'Charakter: {0}', 'cabinet_dip_stat_gdp': 'GDP {0}',
 'cabinet_dip_stat_pop': 'Bev. {0} · Ø {1}', 'cabinet_dip_stat_laws': '{0} Gesetze · {1} Politiken',
 'cabinet_dip_stat_war': 'Im Krieg', 'cabinet_dip_stat_peace': 'Frieden',
 'toast_dip_war': '[Diplomatie] Krieg gegen <{0}> erklärt',
 'toast_dip_already_war': 'Bereits im Krieg',
 'toast_dip_peace': '[Diplomatie] Frieden mit <{0}> (Entschädigung +{1}G)',
 'toast_dip_peace_fail': 'Kein Frieden möglich (nicht im Vorteil / kein Krieg)',
 'toast_dip_alliance': '[Diplomatie] Bündnis mit <{0}>',
 'toast_dip_alliance_refused': 'Bündnis abgelehnt (Beziehungen unzureichend)',
 'toast_dip_gift': '[Diplomatie] Geschenk an <{0}> (Wohlwollen +{1})',
 'toast_dip_gift_poor': 'Schatzkammer zu leer für ein Geschenk',
 'toast_dip_pact_ok': '[Diplomatie] Wirtschaftspakt mit <{0}> geschlossen',
 'toast_dip_pact_cancel': '[Diplomatie] Wirtschaftspakt mit <{0}> beendet',
 'toast_dip_pact_full': 'Pakt-Slots voll (max. 2)',
 'toast_dip_pact_war': 'Kein Pakt mit Kriegsgegner möglich',
 'toast_dip_pact_same': 'Pakt dieser Stufe besteht bereits',
 'toast_dip_failed': 'Diplomatische Aktion fehlgeschlagen',
})

laws_de = {
 'law_trade_freedom': 'Handelspolitik', 'law_property_rights': 'Eigentumsrechte',
 'law_tax_system': 'Steuersystem', 'law_antimonopoly': 'Kartellrecht',
 'law_land_reform': 'Landreform', 'law_education': 'Schulpflicht',
 'law_healthcare': 'Öffentliche Gesundheit', 'law_migrant': 'Migrationspolitik',
 'law_religion': 'Religionspolitik', 'law_press': 'Pressekontrolle',
 'law_gun_control': 'Waffenkontrolle', 'law_conscription': 'Wehrpflicht',
 'law_standing_army': 'Stehendes Heer', 'law_militarism': 'Militarismus',
 'law_pacifism': 'Pazifismus', 'law_judicial': 'Justizunabhängigkeit',
 'law_capital_pun': 'Todesstrafe', 'law_ant_corrupt': 'Antikorruption',
 'law_prison': 'Gefängnisreform', 'law_forest': 'Waldschutz',
 'law_animal': 'Tierschutz', 'law_pollution': 'Umweltschutz',
 'law_monarchy': 'Monarchie', 'law_parliament': 'Parlamentarische Demokratie',
 'law_planned_economy': 'Planwirtschaft', 'law_free_market': 'Freier Markt',
 'law_state_religion': 'Staatsreligion', 'law_secularism': 'Säkularismus',
}
for k, v in laws_de.items():
    t(**{k: v})
tiers_de = {
 'law_trade_freedom_lv0': 'Laissez-faire', 'law_trade_freedom_lv1': 'Freier Markt',
 'law_trade_freedom_lv2': 'Regulierter Markt', 'law_trade_freedom_lv3': 'Strikte Kontrolle',
 'law_trade_freedom_lv4': 'Kommandowirtschaft',
 'law_property_rights_lv0': 'Kein Schutz', 'law_property_rights_lv1': 'Teilweise',
 'law_property_rights_lv2': 'Standard', 'law_property_rights_lv3': 'Stark', 'law_property_rights_lv4': 'Absolut',
 'law_tax_system_lv0': 'Steuerfrei', 'law_tax_system_lv1': 'Niedrig', 'law_tax_system_lv2': 'Mittel',
 'law_tax_system_lv3': 'Hoch', 'law_tax_system_lv4': 'Extrem',
 'law_antimonopoly_lv0': 'Ignorieren', 'law_antimonopoly_lv1': 'Überwachen',
 'law_antimonopoly_lv2': 'Regulieren', 'law_antimonopoly_lv3': 'Zerschlagen', 'law_antimonopoly_lv4': 'Verstaatlichen',
 'law_land_reform_lv0': 'Keine Reform', 'law_land_reform_lv1': 'Schrittweise',
 'law_land_reform_lv2': 'Umfassend', 'law_land_reform_lv3': 'Zwangsenteignung', 'law_land_reform_lv4': 'Vollständige Umverteilung',
}
for k, v in tiers_de.items():
    t(**{k: v})
policies_de = {
 'policy_low_tax': 'Steuersenkung', 'policy_austerity': 'Austerität',
 'policy_subsidy': 'Industriesubventionen', 'policy_trade_deal': 'Merkantilismus',
 'policy_poor_relief': 'Armenfürsorge', 'policy_public_work': 'Öffentliche Arbeiten',
 'policy_family': 'Gebietsförderung', 'policy_festival': 'Fest', 'policy_war_fund': 'Kriegsfonds',
 'policy_recruit': 'Rekrutierung', 'policy_fortify': 'Befestigung', 'policy_border_guard': 'Grenzschutz',
 'policy_diplomacy': 'Diplomatie', 'policy_isolation': 'Isolation', 'policy_expansion': 'Expansionismus',
 'policy_reparations': 'Reparationsdiplomatie',
}
for k, v in policies_de.items():
    t(**{k: v})
styles_de = {
 'style_bellicose': 'Kriegerisch', 'style_merchant': 'Kaufmännisch', 'style_welfare': 'Wohlfahrtsstaat',
 'style_legalist': 'Legalistisch', 'style_isolationist': 'Isolationistisch', 'style_tech': 'Technokratisch',
}
for k, v in styles_de.items():
    t(**{k: v})

t(**{
 'cabinet_tab_bank': 'Bank & Handel',
 'bank_stats_reserves': 'Bankreserven: {0}', 'bank_stats_loans': 'Ausstehende Kredite: {0}',
 'bank_stats_default': 'Ausfälle Vorjahr: {0}%',
 'bank_risk_label': 'Bank-Run-Risiko: {0}',
 'bank_risk_0': 'Sicher', 'bank_risk_1': 'Warnung', 'bank_risk_2': 'Gefahr',
 'bank_rate_label': 'Leitzins', 'bank_rate_high': 'Hoch(sicher)', 'bank_rate_mid': 'Mittel', 'bank_rate_low': 'Niedrig(riskant)',
 'bank_quota_label': 'Kreditvolumen', 'bank_quota_tight': 'Eng', 'bank_quota_mid': 'Mittel', 'bank_quota_loose': 'Weit',
 'bank_reserve_label': 'Reservequote', 'bank_reserve_high': 'Hoch', 'bank_reserve_mid': 'Mittel', 'bank_reserve_low': 'Niedrig',
 'bank_preset_stimulus': 'Stimulans', 'bank_preset_neutral': 'Neutral', 'bank_preset_suppress': 'Restriktiv',
 'bank_preset_applied': 'Bankkanal angepasst',
 'bank_commerce_title': 'Handel', 'bank_commerce_tax': 'Handelssteuer dieses Jahr: {0}',
 'bank_policy_franchise': 'Konzessionsrecht [{0}]', 'bank_policy_fairprice': 'Fairpreisgesetz [{0}]',
 'bank_policy_on': 'AN', 'bank_policy_off': 'AUS',
 'bank_disabled_note': '(Bankwesen ist in den Einstellungen deaktiviert; diese Seite ist nur Anzeige)',
 'toast_event_chain': 'Eine frühere Wahl trägt neue Frucht — {kingdom} trifft eine neue Entscheidung',
})

t(**{
 'cabinet_ruler': 'Regierend: {0}',
 'ruler_trait_greedy': 'Gierig', 'ruler_trait_deceitful': 'Trügerisch', 'ruler_trait_honest': 'Ehrlich',
 'ruler_trait_content': 'Zufrieden', 'ruler_trait_ambitious': 'Ehrgeizig', 'ruler_trait_wise': 'Weise',
 'ruler_trait_none': 'Ordinär',
})

t(**{
 'ev_desc_decision': 'Das Königreich hat entschieden (Option {0}).',
 'toast_event_pending': 'Eine Entscheidung wartet auf das Königreich — öffne das Kabinett.',
 'toast_event_chain': 'Eine frühere Wahl trägt neue Frucht — {kingdom} trifft eine neue Entscheidung',
 'event_choice_title': 'Entscheidung',
 'event_choice_header': '〈{0}〉 Ereignis {1}/{2}',
 'event_choice_kingdom': 'Die Wahl von 〈{0}〉',
 'event_choice_year': 'Jahr {0}',
 'event_choice_countdown': '{0} Jahr(e) übrig, dann wird die vorsichtige Option gewählt',
 'event_choice_none': 'Keine offenen Entscheidungen.',
 'event_choice_next': '{0} weitere offen →',
 'event_choice_cost': 'Kostet {0}', 'event_choice_gain': 'Bringt {0}',
 'event_choice_tax': 'Steuert Einwohner', 'event_choice_relief': 'Armenfürsorge',
 'event_choice_goodwill': 'Wohlwollen {0}{1}', 'event_choice_unrest': 'Erhöht Unruhe',
 'cabinet_pending_row': 'Offene Entscheidungen ×{0} (nächste: {1} J.)',
 'cabinet_pending_open': 'Behandeln',
 'toast_nation_place_mode': 'Platzierungsmodus: {0} | Linksklick platzieren · Rechtsklick abbrechen',
 'toast_nation_place_cancelled': 'Platzierungsmodus beendet',
 'toast_nation_place_land': 'Kann nicht auf Wasser platziert werden',
 'toast_nation_place_territory': 'Nur innerhalb des eigenen Hoheitsgebiets',
 'toast_nation_build_failed': 'Platzierung fehlgeschlagen (ungültige Position)',
 'toast_nation_built': '<{0}> Bau fertig (-{1}G)',
 'toast_nation_built_already': 'In dieser Stadt bereits gebaut',
 'toast_nation_poor_treasury': 'Schatzkammer unzureichend',
 'toast_nation_cooldown': 'Abklingzeit aktiv',
 'toast_nation_no_slot': 'Politik-Slots voll (max. {0})',
 'toast_nation_policy_on': '[Politik] {0} aktiviert (Stufe {1})',
 'toast_nation_policy_off': '[Politik] {0} beendet',
 'toast_nation_policy_suspended': '{0} wegen leerer Schatzkammer ausgesetzt',
 'toast_nation_relief': '[Dekret] Nothilfe verteilt an {0}',
 'toast_nation_festival': '[Dekret] Nationalfest abgehalten (Unruhe gelöscht)',
 'toast_nation_unbind': 'Königreich gefallen — Herrschaft beendet',
 'toast_nation_claim': '[Übernahme] Herrschaft über <{0}> begonnen (Schatzkammer {1})',
 'toast_event_pending': 'Eine Entscheidung wartet auf das Königreich — öffne das Kabinett.',
})

misc_de = {
 'ev_desc_unrest': 'Ungleichheit überschreitet die Schwelle; Unruhe bricht aus ({0})',
 'ev_desc_incite': 'Aufwiegelung löst Unruhe aus ({0})',
 'ev_desc_suppress': 'Unterdrückung durchgeführt',
 'ev_desc_plunder': 'Kriegsplünderung +{0}G',
 'ev_desc_revolution': 'Revolution ausgebrochen ({0})',
 'ev_desc_uprising': 'Straßenaufstand ({0})',
 'ev_desc_build_inv': '{0} tätigt Bauinvestitionen',
 'ev_desc_craft_arsenal': '{0} schmiedet {1} Waffen',
 'ev_desc_wholesale': '{0} verkauft {1} Waffen grob',
 'ev_desc_era_golden': 'Goldenes Zeitalter in {0}',
 'ev_desc_era_revival': '{0} erlebt eine Wiedergeburt',
 'ev_desc_era_flourish': '{0} tritt in eine Blütephase ein',
 'ev_desc_collapse': 'Wirtschaftskollaps in {0}',
 'ev_desc_policy': 'Nationale Politik angepasst',
 'ev_desc_unrest_peace': 'Unruhe durch Verhandlung beigelegt',
 'ev_desc_unrest_resolved': 'Unruhe unterdrückt; Stadt zurückerobert',
 'ev_desc_policy_fail_abdicate': 'Reform gescheitert; der König dankt ab',
 'ev_desc_policy_fail_death': 'Reform gescheitert; der König stirbt',
 'ev_desc_policy_fail_civilwar': 'Reform gescheitert; Bürgerkrieg bricht aus',
 'ev_desc_policy_fail_fiscal': 'Fiskalreform gescheitert',
 'ev_desc_king_inherit': 'Neuer König bestiegen',
 'ev_desc_disaster': 'Katastrophenschock (Verlust {0})',
 'ev_desc_banking': 'Bankkredite & Zahlungsausfälle (Umfang {0})',
 'ev_desc_bubble_burst': 'Wirtschaftsblase geplatzt ({0})',
 'ev_desc_nation_claim': 'Herrschaft über {0} übernommen',
 'ev_desc_nation_policy': '{0} passt Politik an',
 'ev_desc_nation_relief': '{0} gewährt Nothilfe ({1}G)',
 'ev_desc_nation_festival': '{0} veranstaltet ein Nationalfest',
 'ev_desc_nation_build': '{0} errichtet ein Gebäude',
 'ev_desc_nation_diplomacy': 'Diplomatische Aktion von {0} ({1})',
 'ev_desc_law_reform': '{0} reformiert die Gesetze',
 'ev_desc_law_reform_major': '{0} reformiert die Gesetze umfassend',
 'ev_desc_decision': 'Das Königreich hat entschieden (Option {0}).',
 'ev_era_combined': 'Zeitalter-Ereignisse',
 'ev_wholesale': 'Waffengroßhandel',
 'ruler_skim': 'Hofhaltungskosten',
 'nation_commerce_tax': 'Handelssteuer',
}

path = 'Locales/de.json'
existing = json.load(io.open(path, encoding='utf-8'), object_pairs_hook=collections.OrderedDict)
merged = 0
for k, v in DE.items():
    if k not in existing:
        existing[k] = v; merged += 1
json.dump(existing, io.open(path, 'w', encoding='utf-8'), ensure_ascii=False, indent=2)
io.open(path, 'a', encoding='utf-8').write('\n')
print('de merged:', merged, 'total:', len(existing))
