# -*- coding: utf-8 -*-
"""v1.6.0 ja 最終 58 鍵。冪等。"""
import io, json, collections

en = json.load(io.open('Locales/en.json', encoding='utf-8'))
path = 'Locales/ja.json'
existing = json.load(io.open(path, encoding='utf-8'), object_pairs_hook=collections.OrderedDict)

JA = collections.OrderedDict()
def t(**kw): JA.update(kw)

t(**{
 # misc UI
 'col_gdp': 'GDP',
 'toast_dip_alliance_exists': '[外交] すでに同じ同盟に所属',
 'toast_dip_alliance_both': '[外交] 双方すでに同盟あり',
 'nation_claim': '王国の統治',
 'nation_claim_hotkey': '内閣ホットキー',
 'nation_claim_hotkey Description': '地図の王国にホバーしてこのキーで統治/内閣を開く（Unity KeyCode 名、空で無効）',
 'ui_scale': 'UI スケール',
 'ui_scale Description': '内閣パネルのフォントとボタンの全体スケール（0.8-1.6）',
 'nation_build_native': '建築を建てる',
 'toast_law_law_ok': '[法典] 法律を調整',
 'toast_law_policy_ok': '[法典] 国策を調整',
 'toast_law_ai_poor': '[法典] 昇格資金が足りない',
 'toast_law_reform': '[法典] <{0}> が法律を改正',
 'toast_law_reform_major': '[法典] <{0}> が重大な憲法改革！',
 'law_suggest_btn': '→{0}',
 'cabinet_dip_stat_gdp': 'GDP {0}',
 # 残りイベント本文（説明とオプション）
 'ev_tax_farm_desc': 'ある大商人が税吏を包税する代わりに三年分の税金を先払いすると申し出ている。帳面は良くなるが、民心は不定。',
 'ev_tax_farm_opt1': '包税を許可',
 'ev_tax_farm_opt1_desc': '今金を受け取り、不満は後から来る。',
 'ev_tax_farm_opt2': '提案を拒否',
 'ev_tax_farm_opt2_desc': '税吏は王室の下に留まる。',
 'ev_war_bonds_desc': '戦争が破産を迫る：国民に債券を発行し、勝利で償還。',
 'ev_war_bonds_opt1': '債券を発行',
 'ev_war_bonds_opt1_desc': '国民が喜んで購入し、戦費が満たされる。',
 'ev_war_bonds_opt2': '拒否',
 'ev_war_bonds_opt2_desc': '国民に借金を作らず、戦費は骨まで削る。',
 'ev_land_survey_desc': '国庫が全国の田畑の測量を請願：隠された土地と税金が暴かれる。',
 'ev_land_survey_opt1': '測量を承認',
 'ev_land_survey_opt1_desc': '測量士に今支払えば、来年は税基盤が誠実になる。',
 'ev_land_survey_opt2': '延期する',
 'ev_land_survey_opt2_desc': '大騒ぎになる——{king}は古い帳簿を残す。',
 'ev_guild_bank_desc': '手工業ギルドが貸付銀行を望み、王室に出資を求めている。',
 'ev_guild_bank_opt1': '王室が出資',
 'ev_guild_bank_opt1_desc': '出資して配当を受け取る——ギルドと運命を共にする。',
 'ev_guild_bank_opt2': '辞退',
 'ev_guild_bank_opt2_desc': '王室の名を金貸しに出さず、貧民を慰める。',
 'ev_heir_plot_desc': '密報：{king}の後継者が将軍たちに取り入っている。刀は鞘から半分出ている。',
 'ev_heir_plot_opt1': '逮捕する',
 'ev_heir_plot_opt1_desc': '即刻逮捕——廷は震えるが脅威は今日死ぬ。',
 'ev_heir_plot_opt2': '忠誠を買う',
 'ev_heir_plot_opt2_desc': '金と栄誉で野心を飼いならす。',
 'ev_heir_plot_opt3': '見ていて待つ',
 'ev_heir_plot_opt3_desc': '盲目を装い網を張る——蛇を驚かせてはならない。',
 'ev_heir_plot_crushed_desc': '後継者の派閥は砕けたが、残党は各官庁に残る。どうする？',
 'ev_heir_plot_crushed_opt1': '屋敷を没収',
 'ev_heir_plot_crushed_opt1_desc': '全面的に没収し、国庫が膨らむ。',
 'ev_heir_plot_crushed_opt2': '小魚は許す',
 'ev_heir_plot_crushed_opt2_desc': '首謀者のみ罰し、寛大さが感謝を生む。',
 'ev_concubine_rivalry_desc': '二人の妃が公然と争い、諍いが王座に届く。',
 'ev_concubine_rivalry_opt1': '平和を買う',
 'ev_concubine_rivalry_opt1_desc': '両方に贈り物——不安な平和。',
 'ev_concubine_rivalry_opt2': '両方を罰する',
 'ev_concubine_rivalry_opt2_desc': '両方降格して罰し、秩序を回復する。',
 'ev_royal_astrologer_desc': '星占い師が星に大吉兆を読む——祭壇の代金が要る。',
 'ev_royal_astrologer_opt1': '儀式に資金を出す',
 'ev_royal_astrologer_opt1_desc': '用心のため——心の平和を買う。',
 'ev_royal_astrologer_opt2': '追放する',
 'ev_royal_astrologer_opt2_desc': '魔術と呼んで追放；学者は歓喜、祭司は激怒。',
 'ev_hunt_accident_desc': '秋の狩りで{king}の馬が暴走し平民を踏んだ——群衆の前で。',
 'ev_hunt_accident_opt1': '厚く補償',
 'ev_hunt_accident_opt1_desc': '王の礼で葬り、家を訪ねて謝罪する。',
 'ev_hunt_accident_opt2': '法律通りに',
 'ev_hunt_accident_opt2_desc': '官吏に標準額を支払わせる。',
 'ev_hunt_accident_opt3': '口止めする',
 'ev_hunt_accident_opt3_desc': '群衆を散らし、話を埋める。',
 'ev_old_regent_desc': '長年統治した老摂政が引退を請い、廷が息を殺す。',
 'ev_old_regent_opt1': '栄誉を贈る',
 'ev_old_regent_opt1_desc': '金・儀仗を賜い、体面を保つ。',
 'ev_old_regent_opt2': '権を回収',
 'ev_old_regent_opt2_desc': '機に乗じて大権を回収——老臣の恨みが深い。',
 'ev_bastard_claim_desc': '古い証を持った青年が{king}の血筋を称し、宗籍への加入を要求する。',
 'ev_bastard_claim_opt1': '検認',
 'ev_bastard_claim_opt1_desc': '検分して認める——名分と非難が同時に来る。',
 'ev_bastard_claim_opt2': '詐欺として追放',
 'ev_bastard_claim_opt2_desc': '偽造と糾弾し、追い出す。',
 'ev_spy_ring_desc': '内廷が密探網の設置を提言：使節と重臣を監視。',
 'ev_spy_ring_opt1': '資金を認める',
 'ev_spy_ring_opt1_desc': '耳を四方に置く；{king}が真っ先に聞く。',
 'ev_spy_ring_opt2': '不徳として拒否',
 'ev_spy_ring_opt2_desc': '王室は白昼堂々と行動すべき。',
 'ev_war_defector_desc': '敵の老練な将が陣前で寝返り、秘密を差し出す——意図は読めない。',
 'ev_war_defector_opt1': '縛って見せしめ',
 'ev_war_defector_opt1_desc': '陣前で斬り、敵胆を寒からしめる。',
 'ev_war_defector_opt2': '才能を重用',
 'ev_war_defector_opt2_desc': '礼で迎え入れ才能を取る——心は未検。',
 'ev_war_defector_opt3': '礼送する',
 'ev_war_defector_opt3_desc': '受け入れず礼で送り信義を守る。',
 'ev_defector_ambition_desc': '寝返りが兵を擁し、命令に従わない。古い禍根が芽吹いている。',
 'ev_defector_ambition_opt1': '先制で兵権を削る',
 'ev_defector_ambition_opt1_desc': '代価を惜しまず兵権を回収し、後患を断つ。',
 'ev_defector_ambition_opt2': '耐える',
 'ev_defector_ambition_opt2_desc': '粛清は内乱を招く——今は耐える。',
 'ev_supply_convoy_desc': '前線の兵糧隊が襲われ、護送官が増援を懇願する。',
 'ev_supply_convoy_opt1': '護衛を派遣',
 'ev_supply_convoy_opt1_desc': '城中から人手を割いて兵糧路を守る。',
 'ev_supply_convoy_opt2': '人手がない',
 'ev_supply_convoy_opt2_desc': '断り、護送官の幸運を祈る。',
 'ev_fort_rebuild_desc': '国境の古い要塞が崩れかけ、守将が再建を請願する。',
 'ev_fort_rebuild_opt1': '再建を助成',
 'ev_fort_rebuild_opt1_desc': '金を投じて城塞を再建し、辺境が眠れる。',
 'ev_fort_rebuild_opt2': '工事を延期',
 'ev_fort_rebuild_opt2_desc': '辺務は待てる——他に金を使う。',
 'ev_veteran_company_desc': '退役した老兵が常設の辺境守備隊を請願する。ただの給料で。',
 'ev_veteran_company_opt1': '許可する',
 'ev_veteran_company_opt1_desc': '給料を払い、老兵に国境を守らせる。',
 'ev_veteran_company_opt2': '丁重に断る',
 'ev_veteran_company_opt2_desc': '国庫が逼迫——老兵を地元に帰す。',
 'ev_privateer_licence_desc': '海賊の頭領が私掠許可と引き換えに金を差し出す。',
 'ev_privateer_licence_opt1': '許可を出す',
 'ev_privateer_licence_opt1_desc': '金を取って許可；{kingdom}の海に公認の狼が増える。',
 'ev_privateer_licence_opt2': '船を焼く',
 'ev_privateer_licence_opt2_desc': '拒否し見せしめに船を焼く。',
 'ev_hero_funeral_desc': '国境を守った老将が世を去り、国が弔う。儀式の格式が決まらない。',
 'ev_hero_funeral_opt1': '国葬で',
 'ev_hero_funeral_opt1_desc': '国葬で送り、費用は王室が負担。',
 'ev_hero_funeral_opt2': '質素に葬る',
 'ev_hero_funeral_opt2_desc': '遺言に従い、質素に。',
 'ev_market_fire_desc': '夜の市場火災で半分が焼け、商人が元手を失う。',
 'ev_market_fire_opt1': '王室が再建を助成',
 'ev_market_fire_opt1_desc': '王庫金で市場を再建。',
 'ev_market_fire_opt2': '自助に任せる',
 'ev_market_fire_opt2_desc': '市場は自分で再建；王室は一文も出さない。',
 'ev_water_shortage_desc': '乾いた夏が井戸を空にし、毎日長い列ができる。',
 'ev_water_shortage_opt1': '深井戸を掘る',
 'ev_water_shortage_opt1_desc': '井戸掘りに金を払い、深く掘り水を引く。',
 'ev_water_shortage_opt2': '給水を制限',
 'ev_water_shortage_opt2_desc': '戸別に制限——安いが不評。',
 'ev_tenant_strike_desc': '地代が上がりすぎて、小作人が納付を拒否。地主が王廷に訴える。',
 'ev_tenant_strike_opt1': '減租を勧める',
 'ev_tenant_strike_opt1_desc': '王室が地主に減租を圧力。',
 'ev_tenant_strike_opt2': '強制徴収',
 'ev_tenant_strike_opt2_desc': '役人を派遣し、法が先。',
 'ev_festival_request_desc': '民が連名で請願：豊作が来た——{king}に全城の祝祭を許可してほしい。',
 'ev_festival_request_opt1': '祝祭を宣告',
 'ev_festival_request_opt1_desc': '王室金で公共の喜び。',
 'ev_festival_request_opt2': '良い時に節約',
 'ev_festival_request_opt2_desc': '良い時は待てる——悪い時のために残す。',
 'ev_night_patrol_desc': '夜を盗賊が支配し、店が毎晩強盗される。組合が夜回りを要求。',
 'ev_night_patrol_opt1': '夜回り隊を作る',
 'ev_night_patrol_opt1_desc': '夜回りに払い、店に眠りを返す。',
 'ev_night_patrol_opt2': '店の自助に任せる',
 'ev_night_patrol_opt2_desc': '店が自分の護衛を雇う；王室は支払わない。',
 'ev_bathhouse_fad_desc': '浴場ブームが街を席巻；組合が王室の支持を求める。',
 'ev_bathhouse_fad_opt1': '新しい浴場を支援',
 'ev_bathhouse_fad_opt1_desc': '浴場を支援し、街全体の健康へ。',
 'ev_bathhouse_fad_opt2': '流行が去るのを待つ',
 'ev_bathhouse_fad_opt2_desc': '王室は流行を追わない。',
 'ev_traveling_fair_desc': '巡回市が街に入り、王室の許可と課税を求める。',
 'ev_traveling_fair_opt1': '許可する',
 'ev_traveling_fair_opt1_desc': '許可し、王室の分け前を取る。',
 'ev_traveling_fair_opt2': '追い返す',
 'ev_traveling_fair_opt2_desc': '混乱を恐れ、巡回市を断る。',
 'ev_royal_visit_desc': '隣国が王室来訪を発表——華やかさは負けられない。',
 'ev_royal_visit_opt1': '費用を惜しまない',
 'ev_royal_visit_opt1_desc': '国賓の礼遇で全力接待。',
 'ev_royal_visit_opt2': '標準儀礼',
 'ev_royal_visit_opt2_desc': '儀礼どおり——礼儀正しく、豪華でなく。',
 'ev_hostage_request_desc': '強大な同盟が王室の子を人質に送るよう要求——友好の証に。',
 'ev_hostage_request_opt1': '人質を送る',
 'ev_hostage_request_opt1_desc': '王の血を国外へ——宮殿は泣く。',
 'ev_hostage_request_opt2': '柔らかく断る',
 'ev_hostage_request_opt2_desc': '幼さを理由に断り、同盟者が面目を失う。',
 'ev_border_treaty_desc': '隣国が国境条約を提案：境界標を定め、争いを終わらせる。',
 'ev_border_treaty_opt1': '条約に署名',
 'ev_border_treaty_opt1_desc': '争いの土地を譲り、一世紀の平和へ。',
 'ev_border_treaty_opt2': '一寸も譲らない',
 'ev_border_treaty_opt2_desc': '祖先の土地は譲らず、国境警備を倍加。',
 'ev_pirate_bribe_desc': '海賊が条件を送る：払えば{kingdom}の船は安全に航行。',
 'ev_pirate_bribe_opt1': '通行料を払う',
 'ev_pirate_bribe_opt1_desc': '払い、船に安全旗を掲げる。',
 'ev_pirate_bribe_opt2': '代わりに賞金を出す',
 'ev_pirate_bribe_opt2_desc': '海賊の頭に賞金。',
 'ev_pilgrim_wave_desc': '奇跡の噂が巡礼者を{kingdom}の国境へ運ぶ。',
 'ev_pilgrim_wave_opt1': '巡礼者を泊める',
 'ev_pilgrim_wave_opt1_desc': '道端の避難所とスープ。',
 'ev_pilgrim_wave_opt2': '国境を閉じる',
 'ev_pilgrim_wave_opt2_desc': '群衆を恐れ、国境を閉じて追い返す。',
 'ev_tribute_envoy_desc': '遠くの小国が貢物を送り、{kingdom}の保護を求める。',
 'ev_tribute_envoy_opt1': '貢物を受け取る',
 'ev_tribute_envoy_opt1_desc': '贈り物を受け、保護者の義務も負う。',
 'ev_tribute_envoy_opt2': '柔らかく断る',
 'ev_tribute_envoy_opt2_desc': '小国から何も取らず、平等に扱う。',
})

merged = 0
for k, v in JA.items():
    if existing.get(k) == en.get(k):
        existing[k] = v; merged += 1
json.dump(existing, io.open(path, 'w', encoding='utf-8'), ensure_ascii=False, indent=2)
io.open(path, 'a', encoding='utf-8').write('\n')
t2 = sum(1 for k in en if existing.get(k) != en.get(k))
miss = [k for k in en if existing.get(k) == en.get(k)]
print('ja merged:', merged, 'translated:', t2, '/', len(en), '(', round(t2/len(en)*100), '%)', 'remaining:', len(miss))
for k in miss[:8]: print('  still:', k)
