# -*- coding: utf-8 -*-
"""v1.6.0 設定説明 67 キー + toast 33 + picker/unrest/event_type ラベル。冪等。"""
import io, json, collections

en = json.load(io.open('Locales/en.json', encoding='utf-8'))

JA = collections.OrderedDict()
DE = collections.OrderedDict()
def tja(**kw): JA.update(kw)
def tde(**kw): DE.update(kw)

# ===== 設定説明（67）=====
ja_desc = {
 'ui_language Description': 'インターフェース言語：auto = ゲームの言語に従う（デフォルト）',
 'use_chinese_ui Description': 'Mod 言語：ON=中文、OFF=English',
 'unrest_grace_years Description': '最初の N 年間は不安なし',
 'unrest_max_cities Description': '1 回の爆発で蜂起する最大都市数（ランダム増加）',
 'cycle_gini_high Description': '格差がこれ以上 = 不均衡（好況→後退、後退→恐慌）',
 'cycle_gini_low Description': '格差がこれ以下 = 均衡（恐慌/回復は好況へ）',
 'cycle_gini_periods Description': '段階遷移前に持續が要る期間数（少ないほど速い）',
 'boom_stimulus_ratio Description': '好況中に GDP 比で投下されるコイン（信用拡大）',
 'boom_bubble_factor Description': '好況中のバブル蓄積速度（投下×係数）',
 'bubble_threshold Description': '蓄積がこれ超でバブル破裂・コイン蒸発',
 'boom_max_duration Description': '好況が後退に転じるまでの期間数',
 'recession_max_duration Description': '後退が恐慌に転じるまでの期間数',
 'depression_max_duration Description': '恐慌が回復に転じるまでの期間数',
 'recovery_max_duration Description': '回復が好況に転じるまでの期間数',
 'survival_line Description': '平均富がこれ未満で経済が窘迫化',
 'war_plunder_ratio Description': '敗北国のコインを勝利国が略奪する割合',
 'war_waste_ratio Description': '略奪のうち蒸発する割合（戦争ダメージ・移転されない）',
 'revolution_delay_years Description': '反乱がこれ年間続くと国家崩壊',
 'revolution_kill_ratio Description': '革命で処刑される人口割合',
 'uprising_gini_threshold Description': '反乱後、ジニがこれ以上 N 年間続くと街頭蜂起',
 'uprising_delay_years Description': '蜂起前にジニが閾値を超える年数',
 'kill_rich_ratio Description': '蜂起/革命で処刑される最富裕層割合（0.01~0.3）',
 'kill_rich_redist_ratio Description': '処刑された富裕者の富を最貧層へ再分配する割合',
 'wealth_tax_ratio Description': '税線超分への税率（0-0.5）',
 'wealth_tax_line Description': '平均×これ超の市民が納税（1.0-3.0）；平均×0.8 以下は受給',
 'population_overcrowd Description': '人口/容量がこれ以上で過密（0.5-1.0）',
 'era_enabled Description': '盛世/復興/強盛期/崩壊（富裕者消費か周期自動）',
 'era_duration_years Description': '盛世/復興/強盛期の持続年数',
 'collapse_drop_ratio Description': '恐慌中に平均富が前年比これ以上下落で崩壊',
 'collapse_duration_years Description': '崩壊が続く年数',
 'flourish_military_ratio Description': '強盛期の自動発動：戦士/人口がこれ以上',
 'flourish_periods Description': '強盛期発動前に条件が連続する期間数（デバウンス）',
 'labor_wage_base Description': '年俸 = 基本 × 職業倍率（鉱夫1.3/猟師1.1/農夫1.0）',
 'real_time_refresh Description': 'N 秒ごとに統計再計算して HUD 更新（賃金・税なし）',
 'real_time_interval Description': '軽量更新の間隔秒（1-60、デフォルト5）',
 'real_time_refresh_threshold Description': '生存数がこれ以上で再計算スキップ（UI のみ更新）',
 'real_time_refresh_budget Description': '1 回の軽量更新で処理する最大生存数',
 'money_velocity Description': '貨幣供給乗数；高いほどインフレ伝達が速い',
 'inflation_bubble_boost Description': '高インフレでバブル蓄積が加速',
 'disaster_enabled Description': '災害で都市の富が蒸発（人口/都市急減 or ハザードタイル）',
 'disaster_wealth_loss Description': '災害で都市倉庫コインが蒸発する割合',
 'disaster_mine_bonus Description': '好況中の火山地域にボーナスコイン（蒸発分の割合）',
 'credit_rate Description': '借入者が毎年償還する元金割合を利息として',
 'default_rate_depression Description': '恐慌中のデフォルト率（0.1-0.8）',
 'crisis_contagion_threshold Description': 'デフォルト率がこれ超で弱国に感染（0.05-0.5）',
 'spending_cap_per_year Description': '年間処理する富裕者の最大数',
 'banking_default_cap_per_year Description': '年間処理する信用/デフォルト最大王国数',
 'banking_contagion_cap_per_year Description': '年間評価する感染相手最大数',
 'inheritance_scan_per_frame Description': '3 秒ウィンドウ内のフレームごとの最大走査数',
 'frame_budget_ms Description': '年次精算フレーム予算（ms）',
 'cycle_window_ms Description': '精算ウィンドウ（ms）；超過で削減',
 'perf_diagnostics_enabled Description': '年次精算の性能診断（Stopwatch）',
 'cycle_alloc_budget Description': '年次割当予算（KB）',
 'memory_cleanup_enabled Description': '静的スクラッチ/キャッシュの TrimExcess 自動整理',
 'memory_cleanup_force_gc Description': '整理間隔到達時に強制 GC（唯一の GC エントリ）',
 'memory_cleanup_interval_seconds Description': '自動整理の間隔秒（5-300）',
 'memory_cleanup_notify_enabled Description': '解放量が有意（≥0.5MB）または強制 GC 実行時にバナー通知',
 'treasury_income_ratio Description': '都市倉庫から宝物庫へ移す毎期の税負割合',
 'policy_slots Description': '同時に有効な持続政策の最大数',
 'event_chance_player Description': '自国の年次選択イベント発生率（0-1）',
 'event_chance_ai Description': 'AI 王国の年次選択イベント発生率（0-1）',
 'event_cooldown_years Description': '2 つの王国イベント間の最小年数（1-10）',
 'bank_money_supply_factor Description': '貸付純増を貨幣供給へ算入する割合（0-0.5）',
 'bank_max_loans_per_city Description': '都市ごとの貸付残高上限（帳簿有界）',
 'bank_deposit_ratio_default Description': '住民富を都市銀行へ年次預入する割合（0-30）',
 'ruler_personality_enabled Description': '統治者性格：原版の国王特性と性格統計を読み AI の法律・政策・金庫・イベント選択に影響（議会制衡）',
}
tja(**ja_desc)

de_desc = {
 'ui_language Description': 'UI-Sprache: auto = folgt der Spielsprache (Standard)',
 'use_chinese_ui Description': 'Mod-Sprache: ON=Chinesisch, OFF=Englisch',
 'unrest_grace_years Description': 'Keine Unruhen in den ersten N Jahren',
 'unrest_max_cities Description': 'Max. Städte pro Ausbruch (zufällig, wächst mit Gini)',
 'cycle_gini_high Description': 'Kluft darüber = Ungleichgewicht (Boom→Rezession etc.)',
 'cycle_gini_low Description': 'Kluft darunter = Gleichgewicht (Depression→Boom)',
 'cycle_gini_periods Description': 'Perioden, die die Kluft halten muss, bevor der Phasenwechsel erfolgt',
 'boom_stimulus_ratio Description': 'Pro Zyklus injizierte Münzen als GDP-Anteil (Kreditexpansion)',
 'boom_bubble_factor Description': 'Blasenaufbau während des Booms (Injektion × Faktor)',
 'bubble_threshold Description': 'Blase platzt und Münzen verdampfen, wenn der Wert dies überschreitet',
 'boom_max_duration Description': 'Boom wechselt danach zur Rezession',
 'recession_max_duration Description': 'Rezession wechselt danach zur Depression',
 'depression_max_duration Description': 'Depression wechselt danach zur Erholung',
 'recovery_max_duration Description': 'Erholung wechselt danach zum Boom',
 'survival_line Description': 'Wirtschaft verfällt, wenn das Durchschnittsvermögen darunter fällt',
 'war_plunder_ratio Description': 'Anteil der Münzen des Verlierers, den der Sieger plündert',
 'war_waste_ratio Description': 'Anteil der Beute, der verdampft (Kriegsschaden)',
 'revolution_delay_years Description': 'Ein Königreich fällt, wenn der Aufstand so lange dauert',
 'revolution_kill_ratio Description': 'Anteil der Bevölkerung, der bei einer Revolution getötet wird',
 'uprising_gini_threshold Description': 'Wenn die Kluft nach dem Aufstand so lange bleibt, bricht ein Straßenaufstand aus',
 'uprising_delay_years Description': 'Jahre, die die Kluft über der Schwelle bleiben muss',
 'kill_rich_ratio Description': 'Anteil der Reichsten, der bei Aufstand/Revolution hingerichtet wird',
 'kill_rich_redist_ratio Description': 'Anteil des Reichtums Hingerichteter, der den Ärmsten gegeben wird',
 'wealth_tax_ratio Description': 'Steuersatz auf den Betrag über der Steuerlinie (0-0.5)',
 'wealth_tax_line Description': 'Bürger über Ø×dies zahlen Steuer (1.0-3.0)',
 'population_overcrowd Description': 'Überbevölkerung, wenn Bevölkerung/Kapazität ≥ dies',
 'era_enabled Description': 'Goldenes Zeitalter / Wiedergeburt / Blüte / Kollaps',
 'era_duration_years Description': 'Dauer von Goldenem Zeitalter / Wiedergeburt / Blüte',
 'collapse_drop_ratio Description': 'Kollaps, wenn das Ø-Vermögen während Depression so stark fällt',
 'collapse_duration_years Description': 'Dauer des Wirtschaftskollapses',
 'flourish_military_ratio Description': 'Auto-Blüte: Krieger/Bevölkerung ≥ dies',
 'flourish_periods Description': 'Aufeinanderfolgende Zyklen, die die Bedingungen erfüllen (Debounce)',
 'labor_wage_base Description': 'Jahreslohn = Basis × Berufsfaktor (Miner 1.3 etc.)',
 'real_time_refresh Description': 'Statistiken alle N Sekunden neu berechnen und HUD aktualisieren',
 'real_time_interval Description': 'Sekunden zwischen leichtgewichtigen Aktualisierungen (1-60)',
 'real_time_refresh_threshold Description': 'Neuberechnung überspringen, wenn lebende Einheiten dies erreichen',
 'real_time_refresh_budget Description': 'Max. Lebende Einheiten pro Aktualisierung',
 'money_velocity Description': 'Geldmengenmultiplikator; höher = schnellere Inflation',
 'inflation_bubble_boost Description': 'Blasenaufbau beschleunigt sich bei hoher Inflation',
 'disaster_enabled Description': 'Katastrophen lassen Stadtvermögen verdampfen',
 'disaster_wealth_loss Description': 'Anteil der Stadtreserven, der bei Katastrophe verdampft',
 'disaster_mine_bonus Description': 'Vulkanbonus im Boom (Anteil der Verdampfung)',
 'credit_rate Description': 'Zinsanteil, den Kreditnehmer jährlich zurückzahlen',
 'default_rate_depression Description': 'Ausfallrate während Depression (0.1-0.8)',
 'crisis_contagion_threshold Description': 'Bei Überschreitung dieser Rate greift Ansteckung auf schwache Reiche über',
 'spending_cap_per_year Description': 'Max. Reiche pro Jahr verarbeitet',
 'banking_default_cap_per_year Description': 'Max. Königreiche pro Jahr für Kredite/Ausfälle',
 'banking_contagion_cap_per_year Description': 'Max. Ansteckungspartner pro Jahr bewertet',
 'inheritance_scan_per_frame Description': 'Max. Scan pro Frame im 3-Sekunden-Fenster',
 'frame_budget_ms Description': 'Frame-Budget der Jahresabrechnung (ms)',
 'cycle_window_ms Description': 'Abrechnungsfenster (ms); bei Überschreitung Kürzung',
 'perf_diagnostics_enabled Description': 'Performance-Diagnose der Jahresabrechnung (Stopwatch)',
 'cycle_alloc_budget Description': 'Jahreszuweisungsbudget (KB)',
 'memory_cleanup_enabled Description': 'Automatische TrimExcess-Bereinigung statischer Puffer',
 'memory_cleanup_force_gc Description': 'Erzwungenes GC bei Erreichen des Intervalls (einziger GC-Eintrag)',
 'memory_cleanup_interval_seconds Description': 'Sekunden zwischen Bereinigungen (5-300)',
 'memory_cleanup_notify_enabled Description': 'Benachrichtigung, wenn ≥0.5 MB freigegeben oder GC erzwungen',
 'treasury_income_ratio Description': 'Anteil der Stadtreserven, der jede Periode in die Schatzkammer fließt',
 'policy_slots Description': 'Max. gleichzeitig aktive laufende Politiken',
 'event_chance_player Description': 'Jährliche Event-Chance für dein Königreich (0-1)',
 'event_chance_ai Description': 'Jährliche Event-Chance für AI-Königreiche (0-1)',
 'event_cooldown_years Description': 'Mindestjahre zwischen zwei Königreich-Events (1-10)',
 'bank_money_supply_factor Description': 'Anteil des Kreditwachstums, das in die Geldmenge fließt (0-0.5)',
 'bank_max_loans_per_city Description': 'Obergrenze aktiver Kredite pro Stadt',
 'bank_deposit_ratio_default Description': 'Jährlicher Einlagenanteil des Bürgervermögens (0-30)',
 'ruler_personality_enabled Description': 'Herrscherpersönlichkeit: liest Vanille-Königseigenschaften für Gesetze, Politik, Schatzkammer, Events (Parlament bremst)',
}
tde(**de_desc)

# ===== toast 33 + picker/unrest/event_type + misc（共通ラベル）=====
ja_misc = {
 'picker_back': '戻る', 'picker_hint': '選択すると20%の資金が宝物庫へ',
 'picker_kingdom': '王国', 'picker_incite': '扇動', 'picker_suppress': '鎮圧',
 'picker_done': '扇動を実行', 'picker_failed': '実行失敗',
 'picker_done_suppress': '鎮圧を実行', 'picker_failed_suppress': '鎮圧失敗',
 'unrest_state_accum': '不安蓄積', 'unrest_state_active': '不安活性',
 'unrest_state_warning': '不安警告', 'unrest_state_current': '現状',
 'unrest_state_until': 'まで', 'unrest_state_delay': '遅延',
 'unrest_state_no': 'なし', 'unrest_state_trigger': '発動条件',
 'unrest_state_equal': '均等', 'unrest_state_small': '小格差',
 'unrest_state_large': '大格差', 'unrest_state_extreme': '極端',
 'event_family_finance': '財政', 'event_family_disaster': '天災',
 'event_family_court': '宮廷', 'event_family_military': '軍事',
 'event_family_civil': '民生', 'event_family_diplomacy': '外交',
 'settings_title': '古典経済学設定', 'settings_group': '設定',
 'ev_build_inv': '建設投資', 'ev_craft_arsenal': '軍械鍛造',
 'ev_wholesale': '武器卸売', 'ev_era_golden': '盛世', 'ev_era_revival': '復興',
 'ev_era_flourish': '強盛期', 'ev_collapse': '経済崩壊', 'ev_policy': '国家政策',
 'ev_unrest_peace': '暴動和平', 'ev_unrest_resolved': '暴動鎮圧',
 'ev_policy_fail': '改革失敗', 'ev_king_inherit': '王位継承',
 'ev_revolution': '革命', 'ev_uprising': '街頭蜂起', 'ev_bubble_burst': 'バブル破裂',
 'ev_disaster': '災害', 'ev_banking': '銀行危機', 'ev_plunder': '戦争略奪',
 'ev_unrest': '社会不安', 'ev_incite': '扇動', 'ev_suppress': '鎮圧',
 'ev_nation_claim': '王国統治', 'ev_nation_policy': '国家政策',
 'ev_nation_relief': '緊急救済', 'ev_nation_festival': '国慶祭',
 'ev_nation_build': '建築', 'ev_nation_diplomacy': '外交', 'ev_law_reform': '変法',
 'toast_unrest_resolved': '不安は和議で解消された', 'toast_unrest_peace': '不安が鎮圧され都市が回復',
 'toast_policy_redistribute': '[政策] <{0}> 富の再分配を実施',
 'toast_policy_tax_boom': '[政策] <{0}> 好況減税',
 'toast_policy_tax_austerity': '[政策] <{0}> 恐慌増税',
 'toast_policy_fiscal_fail': '[政策] <{0}> 財政改革失敗',
 'toast_policy_tariff': '[政策] <{0}> 関税を徴収（+{1}G）',
 'toast_policy_fail_abdicate': '[改革失敗] <{0}> 国王退位',
 'toast_policy_fail_death': '[改革失敗] <{0}> 国王崩御',
 'toast_policy_fail_civilwar': '[改革失敗] <{0}> 内戦',
 'toast_era_golden': '[時代] <{0}> 盛世到来',
 'toast_era_revival': '[時代] <{0}> 復興',
 'toast_era_flourish': '[時代] <{0}> 強盛期',
 'toast_era_collapse': '[時代] <{0}> 経済崩壊',
 'toast_bubble': '[経済] バブル破裂（{0}）',
 'toast_welfare': '[政策] 福祉', 'toast_wholesale': '[経済] 武器卸売（{0}）',
 'toast_plunder': '[戦争] <{0}> 略奪 +{1}G',
 'toast_kingdom_fall': '[王国] <{0}> 滅亡',
 'toast_inheritance': '[遺産] {0} が {1} を受け継ぐ',
 'toast_era_end': '[時代] <{0}> 盛世終了',
 'dip_pact_tier': '経済協定（第{0}档）',
 'cabinet_dip_pact_tier': '経済協定（第{0}档）',
 'col_rank': '順位', 'col_city': '都市', 'col_export': '輸出', 'col_import': '輸入', 'col_net': '純額',
 'kingdom_law_header': '法典',
}
tja(**ja_misc)

de_misc = {
 'picker_back': 'Zurück', 'picker_hint': 'Wahl überweist 20% der Stadtkassen',
 'picker_kingdom': 'Königreich', 'picker_incite': 'Aufwiegelung', 'picker_suppress': 'Unterdrückung',
 'picker_done': 'Aufwiegelung ausführen', 'picker_failed': 'Aktion fehlgeschlagen',
 'picker_done_suppress': 'Unterdrückung ausführen', 'picker_failed_suppress': 'Unterdrückung fehlgeschlagen',
 'unrest_state_accum': 'Unruhe-Akkumulation', 'unrest_state_active': 'Unruhe aktiv',
 'unrest_state_warning': 'Unruhe-Warnung', 'unrest_state_current': 'Aktuell',
 'unrest_state_until': 'bis', 'unrest_state_delay': 'Verzögerung',
 'unrest_state_no': 'Keine', 'unrest_state_trigger': 'Auslösebedingung',
 'unrest_state_equal': 'Gleich', 'unrest_state_small': 'Kleine Kluft',
 'unrest_state_large': 'Große Kluft', 'unrest_state_extreme': 'Extrem',
 'event_family_finance': 'Finanzen', 'event_family_disaster': 'Katastrophen',
 'event_family_court': 'Hof', 'event_family_military': 'Militär',
 'event_family_civil': 'Zivil', 'event_family_diplomacy': 'Diplomatie',
 'settings_title': 'Klassische Ökonomie Einstellungen', 'settings_group': 'Einstellungen',
 'ev_build_inv': 'Bauinvestition', 'ev_craft_arsenal': 'Waffenschmiede',
 'ev_wholesale': 'Waffengroßhandel', 'ev_era_golden': 'Goldenes Zeitalter', 'ev_era_revival': 'Wiedergeburt',
 'ev_era_flourish': 'Blütezeit', 'ev_collapse': 'Wirtschaftskollaps', 'ev_policy': 'Staatspolitik',
 'ev_unrest_peace': 'Unruhe-Frieden', 'ev_unrest_resolved': 'Unruhe gelöst',
 'ev_policy_fail': 'Reform gescheitert', 'ev_king_inherit': 'Thronfolge',
 'ev_revolution': 'Revolution', 'ev_uprising': 'Straßenaufstand', 'ev_bubble_burst': 'Blasenbruch',
 'ev_disaster': 'Katastrophe', 'ev_banking': 'Bankenkrise', 'ev_plunder': 'Kriegsplünderung',
 'ev_unrest': 'Soziale Unruhe', 'ev_incite': 'Aufwiegelung', 'ev_suppress': 'Unterdrückung',
 'ev_nation_claim': 'Königreichsübernahme', 'ev_nation_policy': 'Staatspolitik',
 'ev_nation_relief': 'Nothilfe', 'ev_nation_festival': 'Nationalfest',
 'ev_nation_build': 'Bau', 'ev_nation_diplomacy': 'Diplomatie', 'ev_law_reform': 'Gesetzesreform',
 'toast_unrest_resolved': 'Unruhe durch Verhandlung beendet', 'toast_unrest_peace': 'Unruhe unterdrückt; Stadt zurück',
 'toast_policy_redistribute': '[Politik] <{0}> Umverteilung durchgeführt',
 'toast_policy_tax_boom': '[Politik] <{0}> Steuersenkung im Boom',
 'toast_policy_tax_austerity': '[Politik] <{0}> Steuererhöhung in der Depression',
 'toast_policy_fiscal_fail': '[Politik] <{0}> Fiskalreform gescheitert',
 'toast_policy_tariff': '[Politik] <{0}> Zoll erhoben (+{1}G)',
 'toast_policy_fail_abdicate': '[Reform gescheitert] <{0}> König dankt ab',
 'toast_policy_fail_death': '[Reform gescheitert] <{0}> König stirbt',
 'toast_policy_fail_civilwar': '[Reform gescheitert] <{0}> Bürgerkrieg',
 'toast_era_golden': '[Zeitalter] <{0}> goldenes Zeitalter',
 'toast_era_revival': '[Zeitalter] <{0}> Wiedergeburt',
 'toast_era_flourish': '[Zeitalter] <{0}> Blütezeit',
 'toast_era_collapse': '[Zeitalter] <{0}> Wirtschaftskollaps',
 'toast_bubble': '[Wirtschaft] Blase geplatzt ({0})',
 'toast_welfare': '[Politik] Wohlfahrt', 'toast_wholesale': '[Wirtschaft] Waffengroßhandel ({0})',
 'toast_plunder': '[Krieg] <{0}> Plünderung +{1}G',
 'toast_kingdom_fall': '[Königreich] <{0}> gefallen',
 'toast_inheritance': '[Erbe] {0} erbt von {1}',
 'toast_era_end': '[Zeitalter] <{0}> goldenes Zeitalter endet',
 'dip_pact_tier': 'Wirtschaftspakt (Stufe {0})',
 'cabinet_dip_pact_tier': 'Wirtschaftspakt (Stufe {0})',
 'col_rank': 'Platz', 'col_city': 'Stadt', 'col_export': 'Export', 'col_import': 'Import', 'col_net': 'Netto',
 'kingdom_law_header': 'Kodex',
}
tde(**de_misc)

# ===== マージ =====
for lang, d in [('ja', JA), ('de', DE)]:
    p = 'Locales/%s.json' % lang
    existing = json.load(io.open(p, encoding='utf-8'), object_pairs_hook=collections.OrderedDict)
    merged = 0
    for k, v in d.items():
        if existing.get(k) == en.get(k):
            existing[k] = v; merged += 1
    json.dump(existing, io.open(p, 'w', encoding='utf-8'), ensure_ascii=False, indent=2)
    io.open(p, 'a', encoding='utf-8').write('\n')
    t2 = sum(1 for k in en if existing.get(k) != en.get(k))
    miss = [k for k in en if existing.get(k) == en.get(k)]
    print(lang, 'merged:', merged, 'translated:', t2, '/', len(en), '(', round(t2/len(en)*100), '%)', 'remaining:', len(miss))
