# -*- coding: utf-8 -*-
"""v1.7.0 military 文案（六语）"""
EVENTS = {}
def ev(eid, opts, title, desc, *texts):
    EVENTS[eid] = (opts, title, desc, list(texts))
def q(*args): return args

ev('sword_guild', 2,
 ('剑匠之争', '劍匠之爭', 'The Sword Guild', 'Гильдия мечников', '剣匠の争い', 'Die Schwertgilde'),
 ('{king}面前摆着一桩军械之争：剑匠行会请独揽王室军械之权，王廷为此争论不休。', '{king}面前擺著一樁軍械之爭：劍匠行會請獨攬王室軍械之權，王廷為此爭論不休。', 'A rivalry of arms lies before {king}: the sword guild asks to monopolize royal weapons, and the court is split.', 'Перед {king} спор оружия: гильдия мечников просит монополию на царское оружие, и двор расколот.', '{king}の前に武器争いが持ち上がる——剣匠組合が王室武具の独占を求め、廷は割れている。', 'Ein Waffenstreit liegt vor {king}: Die Schwertgilde fordert das Monopol auf die königlichen Waffen, der Hof ist gespalten.'),
 q('允其专营', '允其專營', 'Grant the monopoly', 'Дать монополию', '専営を許す', 'Monopol gewähren'),
 q('许行会独占军械铸冶，工价军费俱可议。', '許行會獨佔軍械鑄冶，工價軍費俱可議。', 'Let the guild rule the royal forge; prices and wages are all negotiable.', 'Позволить гильдии вести царскую кузню; цены и жалование обсудимы.', '組合に王室の工房を任せ、値段も賃金も話し合う。', 'Der Gilde die königliche Schmiede überlassen; Preise und Lohn sind verhandelbar.'),
 q('行会感恩，军械精良，列国称{kingdom}器利。', '行會感恩，軍械精良，列國稱{kingdom}器利。', 'The guild is grateful; blades are fine, and realms praise the steel of {kingdom}.', 'Гильдия благодарна; клинки отличны, и соседи хвалят сталь {kingdom}.', '組合は喜び、剣は精良に——諸国は{kingdom}の刃を讃えた。', 'Die Gilde dankt; die Klingen sind vortrefflich, und Reiche loben den Stahl von {kingdom}.'),
 q('严拒私擅', '嚴拒私擅', 'Refuse the claim', 'Отказать гильдии', '特権を拒む', 'Privileg verweigern'),
 q('收回特权，行会哗然，恐生事端。', '收回特權，行會譁然，恐生事端。', 'Revoke the privilege; the guild raises an outcry, and trouble threatens.', 'Лишить привилегии; гильдия зашумит, возможны волнения.', '特権を取り上げれば組合が騒ぎ、事の起こりも恐れられる。', 'Das Vorrecht entziehen; die Gilde lärmt, und Ärger droht.'),
 q('行会怨声鼎沸，工匠罢市，军心浮动。', '行會怨聲鼎沸，工匠罷市，軍心浮動。', 'The guild fumes, the smiths strike, and the soldiers\' hearts waver.', 'Гильдия ропщет, кузнецы бастуют; армия шатка.', '組合が激怒し職人が打ち壊し、軍心は揺らいだ。', 'Die Gilde kocht, die Schmiede streiken, die Herzen der Soldaten wanken.')
)
ev('armor_works', 2,
 ('甲坊之争', '甲坊之爭', 'The Armor Works', 'Броневые мастерские', '甲冑工房の争い', 'Die Panzerwerke'),
 ('军械之争再起：甲胄工坊请求兼营商货以自养，{king}须定其去留。', '軍械之爭再起：甲胄工坊請求兼營商貨以自養，{king}須定其去留。', 'The arms rivalry rises again: the armor works ask to sell wares openly to sustain themselves — {king} must rule.', 'Спор оружия вновь: мастерские просят торговать броней ради самообеспечения — {king} должен решить.', '武器争いは再び——甲冑工房が市に売ることを願い出る。{king}の裁定が待たれる。', 'Der Waffenstreit erneut: Die Panzerwerke bitten, offen zu handeln, um sich zu tragen — {king} muss richten.'),
 q('开放商营', '開放商營', 'Open the market', 'Открыть торговлю', '商売を許す', 'Handel erlauben'),
 q('许工坊贩甲于市，工费与军资皆有着落。', '許工坊販甲於市，工費與軍資皆有著落。', 'Allow them to sell armor; both wages and war funds find their footing.', 'Разрешить продажу брони; жалование и военные средства в порядке.', '甲冑の市販を許せば、職人の給与も軍費も安泰になる。', 'Offen Panzer verkaufen lassen; Lohn und Kriegskasse finden ihr Auskommen.'),
 q('商路大开，{kingdom}金库充盈，甲胄畅销列国。', '商路大開，{kingdom}金庫充盈，甲胄暢銷列國。', 'Trade flows; the treasury of {kingdom} swells, and armor sells across the realms.', 'Торговля идёт; казна {kingdom} полнится, броня расходится по странам.', '商路が開き{kingdom}の国庫は潤い、甲冑は諸国に売れた。', 'Der Handel fließt; die Schatzkammer von {kingdom} schwillt, Panzer finden Absatz.'),
 q('严禁私售', '嚴禁私售', 'Forbid private sale', 'Запретить частную продажу', '私売を禁ず', 'Privatverkauf verbieten'),
 q('禁其市易，工坊亏空，匠人纷纷离坊。', '禁其市易，工坊虧空，匠人紛紛離坊。', 'Ban the trade; the works run short, and smiths drift away.', 'Запретить торг; мастерские пустеют, кузнецы разбегаются.', '市での取引を禁じれば工房は欠損し、職人が離散する。', 'Den Handel verbieten; die Werke verarmen, Schmiede ziehen fort.'),
 q('匠户逃散，甲胄虚耗，军中怨气渐生。', '匠戶逃散，甲胄虛耗，軍中怨氣漸生。', 'Craftsmen scatter, armor runs thin, and the army\'s grumbling grows.', 'Мастера бегут, брони не хватает; армия ворчит.', '職人が逃げ甲冑が乏しくなり、軍に不満が募った。', 'Handwerker laufen auseinander, Panzer fehlen; das Heer murrt.')
)
ev('archer_lodge', 2,
 ('弓箭之社', '弓箭之社', 'The Archer Lodge', 'Лучный дом', '弓社の栄光', 'Der Bogenschützenbund'),
 ('军械之争中，弓箭社自成一体，请{king}准其自设营规、广纳子弟。', '軍械之爭中，弓箭社自成一体，請{king}准其自設營規、廣納子弟。', 'Amid the arms rivalry the Archer Lodge stands apart, asking {king} to keep its own rules and recruit freely.', 'В споре оружия Лучный дом держится особо и просит у {king} своё уложение и свободный набор.', '武器争いの中で弓社は独自の道を行き、{king}に自らの規約と自由な門弟募集を願い出る。', 'Im Waffenstreit steht der Bogenschützenbund für sich und bittet {king} um eigene Satzung und freie Werbung.'),
 q('准社自治', '准社自治', 'Grant it autonomy', 'Дать самоуправление', '自治を認める', 'Autonomie gewähren'),
 q('许其自定营规，社众感戴，射艺日精。', '許其自定營規，社眾感戴，射藝日精。', 'Let it frame its own rules; the lodge is grateful and its archery sharpens.', 'Позволить свой устав; дом благодарен, стрельба становится острее.', '独自の規約を許せば社中は感激し射術が磨かれる。', 'Eigene Satzung erlauben; der Bund dankt, die Schießkunst schärft sich.'),
 q('弓箭社名震四方，列国争向{kingdom}输诚。', '弓箭社名震四方，列國爭向{kingdom}輸誠。', 'The lodge\'s fame rings far; realms turn well-disposed toward {kingdom}.', 'Слава дома гремит; соседи благоволят {kingdom}.', '弓社の名は広く知られ、諸国が{kingdom}に好意を寄せた。', 'Der Ruhm des Bundes dröhnt; Reiche blicken wohlwollend auf {kingdom}.'),
 q('不予理会', '不予理會', 'Ignore the plea', 'Оставить без ответа', '聞き流す', 'Überhören'),
 q('搁置其请，社中默默，依旧自守。', '擱置其請，社中默默，依舊自守。', 'File the request away; the lodge stays quiet and keeps to itself.', 'Отложить просьбу; дом молчит и держится сам.', '願いを保留すれば社は静かに自らを守る。', 'Die Bitte liegen lassen; der Bund bleibt still und hält sich selbst.'),
 q('弓箭社寂然如故，未生风波，也未增荣光。', '弓箭社寂然如故，未生風波，也未增榮光。', 'The lodge stays still as before — no storm comes, and no glory either.', 'Дом тих, как прежде — ни бури, ни славы.', '弓社は変わらず静か——波風もなく栄光もない。', 'Der Bund bleibt ruhig wie zuvor — kein Sturm, kein Glanz.')
)
ev('wage_arrears', 2,
 ('欠饷风波', '欠餉風波', 'The Arrears', 'Задержка жалования', '給金の滞り', 'Der Soldrückstand'),
 ('战事胶着，{kingdom}军饷已欠三月——营中哗声渐起，军心浮动，{king}须早决速断。', '戰事膠著，{kingdom}軍餉已欠三月——營中譁聲漸起，軍心浮動，{king}須早決速斷。', 'The war grinds on; {kingdom}\'s pay is three months late — murmur rises in the camp, and {king} must decide fast.', 'Война буксует; армии {kingdom} не платят три месяца — в лагере ропот, и {king} должен спешить.', '戦況は膠着し{kingdom}の兵への給金は三ヶ月滞る——陣中にざわめきが立ち、{king}の迅速な裁断が要る。', 'Der Krieg mahlt; der Sold von {kingdom} steht seit drei Monaten aus — Murren im Lager, {king} muss schnell entscheiden.'),
 q('补发军饷', '補發軍餉', 'Pay the arrears', 'Выплатить долг', '給金を払う', 'Nachzahlung'),
 q('倾库补发三月饷银，士伍欢然，国库因此受损。', '傾庫補發三月餉銀，士伍歡然，國庫因此受損。', 'Empty the treasury to pay three months of wages; the men rejoice while the purse aches.', 'Отдать три месяца жалования; солдаты рады, казна пустеет.', '庫を割いて三ヶ月分を払えば兵は喜ぶが国庫は痛む。', 'Die Kasse leeren für drei Monate Sold; die Männer jubeln, der Beutel leidet.'),
 q('饷银足发，军心暂安——祸根是否拔除，尚待来日。', '餉銀足發，軍心暫安——禍根是否拔除，尚待來日。', 'Wages in hand, the army rests a while — whether the root is pulled, the days will tell.', 'Деньги в руках, армия спокойна — вырван ли корень, покажут дни.', '給金が届き軍はしばし安らぐ——禍根が抜けたかは来日に問われる。', 'Sold in Händen, das Heer ruht eine Weile — ob die Wurzel beseitigt ist, zeigen die Tage.'),
 q('暂缓不发', '暫緩不發', 'Delay again', 'Снова отложить', 'また延ばす', 'Erneut verschieben'),
 q('以战事吃紧为由缓发，士卒积怨，呼噪愈烈。', '以戰事吃緊為由緩發，士卒積怨，呼噪愈烈。', 'Plead the hard war and hold the pay; the men nurse grudges and the shouting swells.', 'Сослаться на тяготы войны; злость копится, крик растёт.', '戦さの苦しさを理由に延ばせば、恨みは深まり叫びは高まる。', 'Auf den harten Krieg verweisen; der Groll gärt, das Geschrei schwillt.'),
 q('军中怨声愈高，夜有哗变之兆——余波未平，难言吉凶。', '軍中怨聲愈高，夜有譁變之兆——餘波未平，難言吉凶。', 'Grumbling runs high; at night the wind of mutiny stirs — the aftermath lies unwritten.', 'Ропот всё выше; по ночам веет бунтом — чем кончится, неведомо.', '不満が高まり、夜ごとに叛乱の兆し——余波は静まらず吉凶は言えぬ。', 'Das Murren steigt; nachts weht der Wind der Meuterei — was folgt, steht offen.')
)
ev('mutiny_quell', 2,
 ('哗变之秋', '譁變之秋', 'The Mutiny', 'Мятеж в лагере', '兵の反乱', 'Die Meuterei'),
 ('欠饷终酿哗变：一营兵卒反于营门。{king}须立断，怀柔或弹压。', '欠餉終釀譁變：一營兵卒反於營門。{king}須立斷，懷柔或彈壓。', 'The arrears crack at last: a battalion mutinies at the camp gate. {king} must judge — mercy or iron.', 'Задержка жалования обернулась мятежом: батальон восстал у ворот лагеря. {king} должен судить — милость или железо.', '給金の滞りは遂に叛乱を生んだ——一隊が陣門で刃を向ける。{king}は甘くするか鉄で臨むか、即断を迫られる。', 'Der Soldrückstand platzt endlich: Ein Bataillon meutert am Lagertor. {king} muss richten — Milde oder Eisen.'),
 q('严刑弹压', '嚴刑彈壓', 'Crush by law', 'Давить железом', '鉄で弾圧', 'Mit Eisen niederschlagen'),
 q('斩首魁，连坐余党，军心震肃而怨根复埋。', '斬首魁，連坐餘黨，軍心震肅而怨根復埋。', 'Behead the ringleaders and punish the rest; the ranks quail while grudges re-root.', 'Казнить вожаков и наказать остальных; ряды вздрагивают, обиды укоряются вновь.', '首謀者を斬り残党を連座で罰すれば、兵は震え怨みを新たに埋める。', 'Rädelsführer enthaupten, die übrigen strafen; die Ränge erbeben, der Groll wurzelt neu.'),
 q('哗变暂平，然刑威之下暗流涌动，乱象未除。', '譁變暫平，然刑威之下暗流湧動，亂象未除。', 'The mutiny dies down, yet fierce currents run beneath the iron — disorder is not gone.', 'Мятеж стих, но под железом клубится глухая ярость — смута не ушла.', '反乱は鎮まるが圧政の下で暗い怒りが渦巻き、乱の兆しは消えない。', 'Die Meuterei ebbt, doch unter dem Eisen gärt stille Wut — die Unruhe ist nicht fort.'),
 q('许饷抚众', '許餉撫眾', 'Pay and pardon', 'Заплатить и простить', '給金で宥める', 'Zahlen und vergeben'),
 q('许以欠饷并赦其罪，众人释兵，所费颇巨。', '許以欠餉並赦其罪，眾人釋兵，所費頗鉅。', 'Promise the arrears and amnesty; the men lay down arms, and the cost is high.', 'Пообещать долг и амнистию; солдаты слагают оружие, цена высока.', '滞給と恩赦を約束すれば兵は武器を収めるが費用は高い。', 'Sold und Amnestie versprechen; die Männer entwaffnen sich, der Preis ist hoch.'),
 q('众怒稍解，兵刃归鞘；库帑则添一大亏空。', '眾怒稍解，兵刃歸鞘；庫帑則添一大虧空。', 'Anger eases and blades return to sheaths; the treasury takes a deep deficit.', 'Гнев спадает, клинки в ножнах; казна несёт глубокий дефицит.', '怒りは静まり刀は鞘に——国庫は大きな欠損を負った。', 'Der Zorn legt sich, Klingen kehren in die Scheiden; die Kasse trägt ein tiefes Loch.')
)
ev('levy_call', 2,
 ('征发之令', '徵發之令', 'The Call to Levy', 'Призыв в войско', '兵力の徴発', 'Der Aushebungsbefehl'),
 ('前线吃紧，须速补兵。{king}欲举国征丁，或欲重金募客兵授甲。', '前線吃緊，須速補兵。{king}欲舉國徵丁，或欲重金募客兵授甲。', 'The front runs short and men must be raised at once: {king} may conscript the realm or hire mercenaries.', 'Фронт пустеет, а людей нужно собрать срочно: {king} может созвать ополчение или нанять наёмников.', '前線が手薄——直ちに兵を集めねばならぬ。{king}は国民を徴兵するか、金で傭兵を募るか。', 'Die Front wird dünn, Männer müssen sofort her: {king} kann das Land ausheben oder Söldner werben.'),
 q('强征壮丁', '強徵壯丁', 'Conscript the men', 'Созывать ополчение', '壮丁を徴す', 'Bauern ausheben'),
 q('征丁入营，民怨四起，田畴多荒。', '徵丁入營，民怨四起，田疇多荒。', 'Draft the peasantry; resentment rises and the fields lie fallow.', 'Забрать крестьян; ропот растёт, поля пустеют.', '農民を徴兵すれば村の恨みを買い田畑が荒れる。', 'Die Bauern ausheben; der Groll steigt, die Felder veröden.'),
 q('兵额虽足，乡里鼎沸，怨声渐成乱象。', '兵額雖足，鄉里鼎沸，怨聲漸成亂象。', 'The ranks are filled, but villages seethe and resentment ripens into disorder.', 'Ряды полны, но сёла кипят — злоба зреет в смуту.', '兵は揃うが里は騒然とし、怨みが乱へと熟す。', 'Die Ränge füllen sich, doch die Dörfer sieden; der Groll reift zur Unordnung.'),
 q('厚币募兵', '厚幣募兵', 'Hire with gold', 'Нанять за золото', '金で傭兵を募る', 'Mit Gold werben'),
 q('出金募雇佣军，兵源足而金库耗。', '出金募雇傭軍，兵源足而金庫耗。', 'Pay gold for mercenaries; soldiers come in plenty and the treasury thins.', 'Заплатить наёмникам; солдаты приходят вдоволь, казна тощает.', '金で傭兵を集めれば兵は揃うが国庫は減る。', 'Gold an Söldner zahlen; Soldaten kommen reichlich, die Kasse dünnt.'),
 q('募兵立就，军势复振；国库则损费颇钜。', '募兵立就，軍勢復振；國庫則損費頗鉅。', 'The recruits stand and the host revives; the treasury bears a heavy cost.', 'Войско стоит, армия оживает; казна несёт тяжкий расход.', '兵は揃い軍勢は立ち直る——国庫の損耗は大きい。', 'Die Truppen stehen, das Heer lebt auf; die Kasse trägt schwere Kosten.')
)
ev('border_watch', 2,
 ('边备之议', '邊備之議', 'The Border Watch', 'Стража границы', '辺境の備え', 'Die Grenzwacht'),
 ('北疆告警，边境戍防既已旷废。{king}欲整饬烽燧，所费不赀。', '北疆告警，邊境戍防既已曠廢。{king}欲整飭烽燧，所費不貲。', 'The north reports alarms; the border posts lie neglected. {king} may rebuild the beacons — at no small cost.', 'Север тревожит; пограничные посты заброшены. {king} может укрепить маяки — ценой немалой.', '北の方に警報——国境の烽火は荒れ果てる。{king}は費用をかけて立て直すか。', 'Der Norden schlägt Alarm; die Grenzposten liegen vernachlässigt. {king} kann die Zeichen neu bauen — um keinen kleinen Preis.'),
 q('增筑戍垒', '增築戍壘', 'Fortify the line', 'Укрепить рубеж', '砦を増築する', 'Die Linie befestigen'),
 q('出资增垒戍边，烽燧相望，边患可弭。', '出資增壘戍邊，烽燧相望，邊患可弭。', 'Spend on forts and watch-posts; beacons link eye to eye and border ills subside.', 'Потратиться на форты и маяки; дозор перекликается, беды у границы спадают.', '金を出して砦と烽火を整えれば、見張りが続き辺患は治まる。', 'Geld für Türme und Zeichen; die Wachen reichen von Auge zu Auge, die Grenznot ebbt.'),
 q('防线重整，斥候远达；金币则化为砖石。', '防線重整，斥候遠達；金幣則化為磚石。', 'The line stands renewed, scouts reach far; the gold has turned into stone.', 'Рубеж обновлён, дозоры далеки; золото стало камнем.', '防衛線は立て直され斥候は遠くまで——金は石に変わった。', 'Die Linie steht erneuert, Späher reichen weit; Gold ward zu Stein.'),
 q('因循旧制', '因循舊制', 'Keep the old way', 'Соблюдать прежнее', '旧制のまま', 'Altes bewahren'),
 q('不改旧规，戍卒依旧，视其自然。', '不改舊規，戍卒依舊，視其自然。', 'Change nothing; the garrisons stand as before and fate takes its course.', 'Ничего не менять; гарнизоны стоят как прежде, судьба сама правит.', '何も変えず駐屯兵は今のまま、成り行きに任せる。', 'Nichts ändern; die Garnisonen stehen wie zuvor, das Schicksal waltet.'),
 q('边备如常，未添祸患，亦未增一卒之威。', '邊備如常，未添禍患，亦未增一卒之威。', 'The border holds as ever — no new perils, and no new strength either.', 'Граница держится как всегда — ни бед, ни новых сил.', '国境は従来どおり——禍も無ければ新たな力もない。', 'Die Grenze hält wie eh — keine neue Not, keine neue Kraft.')
)
ev('veteran_pension', 2,
 ('老兵抚恤', '老兵撫卹', 'The Veterans\' Pension', 'Пенсия ветеранам', '古兵の恩給', 'Die Veteranenrente'),
 ('解甲老兵聚于都门，索要安家之恩。{king}抚恤与否，系乎军心。', '解甲老兵聚於都門，索要安家之恩。{king}撫卹與否，係乎軍心。', 'Discharged veterans gather at the gate and demand their settlement. {king}\'s grace or refusal will quell or stir the army.', 'Демобилизованные ветераны толпятся у ворот, требуя расчёта. Милость или отказ {king} успокоит армию или взволнует её.', '退役の老兵たちが都の門に集い、扶助を求める。{king}が与えるか否かで軍心が決まる。', 'Ausgemusterte Veteranen drängen sich am Tor und fordern ihre Versorgung. Gnade oder Ablehnung von {king} beruhigt das Heer oder erregt es.'),
 q('厚赏解甲', '厚賞解甲', 'Pay them off', 'Выплатить серебро', '金を贈る', 'Auszahlen'),
 q('发银抚恤，老兵感泣，而内帑为之一空。', '發銀撫卹，老兵感泣，而內帑為之一空。', 'Grant silver and gratitude; the veterans weep while the inner treasury stands empty.', 'Дать серебро и благодарность; ветераны плачут, а внутренняя казна пустеет.', '銀を渡せば老兵は泣いて喜ぶが、内庫は空になる。', 'Silber und Dank gewähren; die Veteranen weinen, die innere Kasse steht leer.'),
 q('老兵各得其所，归乡皆称颂{kingdom}之义。', '老兵各得其所，歸鄉皆稱頌{kingdom}之義。', 'Each veteran finds his place and goes home praising the righteousness of {kingdom}.', 'Каждый ветеран находит своё место и уходит домой, славя справедливость {kingdom}.', '老兵はそれぞれに落ち着き、故郷で{kingdom}の情義を謳った。', 'Jeder Veteran findet seinen Platz und zieht heim, die Gerechtigkeit von {kingdom} zu rühmen.'),
 q('分文不给', '分文不給', 'Send them away', 'Отослать ни с чем', '追い返す', 'Fortschicken'),
 q('斥其归乡自谋，老兵愤愤，营中哗然。', '斥其歸鄉自謀，老兵憤憤，營中譁然。', 'Bid them fend for themselves; the veterans fume and the camps buzz aloud.', 'Велеть кормиться самим; ветераны злятся, лагерь гудит.', '自ら身を立てよと言えば、老兵は憤り陣中がざわめく。', 'Heißen, selbst zu sehen; die Veteranen grollen, die Lager summen laut.'),
 q('老兵结怨于街巷，怨声随唾沫传遍军营。', '老兵結怨於街巷，怨聲隨唾沫傳遍軍營。', 'The veterans nurse their wrath through the alleys, and the murmur carries into every camp.', 'Ветераны копят злобу по улочкам, и ропот уносится в каждый лагерь.', '老兵は路地に恨みを残し、囁きが全陣へと流れた。', 'Die Veteranen hegen Zorn in den Gassen, und das Murmeln trägt in jedes Lager.')
)
ev('marching_training', 2,
 ('行军操典', '行軍操典', 'Marching Drills', 'Маршевые учения', '行軍の訓練', 'Marschdisziplin'),
 ('久不经战，行伍晦慢。{king}欲整军法、命行大操，耗资不赀。', '久不經戰，行伍晦慢。{king}欲整軍法、命行大操，耗資不貲。', 'Long peace has dulled the ranks. {king} may renew the drill code and hold a great review — at no small expense.', 'Долгий мир размягчил ряды. {king} может обновить устав и провести великий смотр — ценой немалой.', '久しい平和で部隊は鈍り気味。{king}は軍法を立て直し大演習を行うか——費用は大きい。', 'Langer Frieden hat die Ränge stumpf gemacht. {king} kann Exerzierordnung erneuern und eine große Heerschau halten — um keinen kleinen Preis.'),
 q('兴师操练', '興師操練', 'Hold the drills', 'Провести учения', '訓練を実施', 'Exerzieren lassen'),
 q('发饷开操，成法重立，军容为之一新。', '發餉開操，成法重立，軍容為之一新。', 'Pay the men and reopen the drills; the old law is restated and the host shines anew.', 'Платить и учить, устав повторить; войско блистает заново.', '給金を払い教練を重ね、古い法を立て直せば軍容が一新する。', 'Sold zahlen und exerzieren, die alte Ordnung neu fassen; das Heer glänzt frisch.'),
 q('步伐齐整，号令如一；铜钱换得铁军。', '步伐齊整，號令如一；銅錢換得鐵軍。', 'Step and order run as one; a few copper coins have bought an army of iron.', 'Шаг и приказ в лад; медяки купили железное войско.', '歩調と号令が揃う——銭が鉄の軍を買った。', 'Schritt und Befehl laufen eins; Kupfer hat ein eisernes Heer gekauft.'),
 q('安于现状', '安於現狀', 'Let things lie', 'Оставить как есть', '現状に甘んじる', 'Liegen lassen'),
 q('不兴操典，军心涣散，习于逸乐。', '不興操典，軍心渙散，習於逸樂。', 'Skip the drill; the men grow scattered and used to ease.', 'Пропустить учения; люди разбредаются и привыкают к покою.', '教練を行わなければ兵は散漫になり安逸に慣れる。', 'Das Exerzieren auslassen; die Männer zersplittern und gewöhnen sich an Muße.'),
 q('操练如常未进，惰气渐生，军容日靡。', '操練如常未進，惰氣漸生，軍容日靡。', 'No drill, no progress; laziness creeps in and the host\'s bearing sags day by day.', 'Учений нет и выгоды нет; лень ползёт, выправка обвисает день ото дня.', '進歩は無く、怠惰が忍び寄り軍容は日に日に緩む。', 'Keine Übung, kein Fortschritt; Trägheit kriecht, die Haltung hängt Tag für Tag.')
)
ev('general_rivalry', 2,
 ('将相不和', '將相不和', 'The Generals\' Quarrel', 'Ссора генералов', '将の不和', 'Der Generalszwist'),
 ('两位宿将争功于帐前，各立山头。{king}偏袒其一，或为军中留患。', '兩位宿將爭功於帳前，各立山頭。{king}偏袒其一，或為軍中留患。', 'Two veteran generals fight for honor before the tent, each with his own hill. Favoring one may leave a canker in the host.', 'Два ветерана ссорятся за честь перед шатром, у каждого свой холм. Поддержка одного может оставить язву в войске.', '二人の老将が幕前で功を争い、それぞれに山を持つ。{king}が片方を持てば軍中に禍根が残るかも。', 'Zwei Veteranen streiten um Ehre vor dem Zelt, jeder auf seinem eigenen Hügel. Einem zu helfen, kann ein Geschwür im Heer lassen.'),
 q('扶其一派', '扶其一派', 'Favor one', 'Поддержать одного', '一方を持ち上げる', 'Einen bevorzugen'),
 q('明诏褒其一将，克日督师——另一将衔恨。', '明詔褒其一將，克日督師——另一將銜恨。', 'Praise one general by edict and charge him with the host — the other swallows gall.', 'Восхвалить одного указом и вверить ему войско; другой глотает желчь.', '詔で一方を賛え軍を預ければ、もう一人は恨みを呑む。', 'Den einen per Erlass preisen und ihm das Heer anvertrauen; der andere schluckt Galle.'),
 q('营中党附渐成，暗斗不休，军令时出歧义。', '營中黨附漸成，暗鬥不休，軍令時出歧義。', 'Factions harden and feuds run on; military orders now speak with two tongues.', 'Клики крепнут, вражда тлеет; приказы заговорили двумя языками.', '派閥が育ち暗闘が続き、軍令が二つの言葉を語る。', 'Parteien verhärten, Fehden glimmen; Befehle reden mit zwei Zungen.'),
 q('两存抚之', '兩存撫之', 'Hold both close', 'Придержать обоих', '両方を撫でる', 'Beide halten'),
 q('双方各予褒赏，谕以共济时艰。', '雙方各予褒賞，諭以共濟時艱。', 'Honor both and bid them share the burdens of the hour.', 'Похвалить обоих и призвать к общим трудам часа.', '双方を褒めて艱難を共にせよと諭す。', 'Beide ehren und sie mahnen, die Lasten der Stunde zu teilen.'),
 q('二将暂敛锋铓，列国闻{kingdom}将相辑睦。', '二將暫斂鋒鋩，列國聞{kingdom}將相輯睦。', 'Both sheathe their edges; realms hear that generals and ministers of {kingdom} stand in harmony.', 'Оба прячут остриё; соседи слышат, что генералы и министры {kingdom} в согласии.', '二将は刃を収め、諸国は{kingdom}の将相和睦を聞く。', 'Beide verbergen die Klinge; Reiche hören, dass Generäle und Minister von {kingdom} in Eintracht stehen.')
)
ev('siege_test', 2,
 ('攻城之试', '攻城之試', 'The Siege Trial', 'Испытание осады', '攻城の試し', 'Die Belagerungsprobe'),
 ('新造冲车云梯已成，{king}欲试其锋芒，须一场实兵演练，费帑不轻。', '新造衝車雲梯已成，{king}欲試其鋒芒，須一場實兵演練，費帑不輕。', 'New rams and towers stand ready; {king} would put their edge to the test in a live drill — no light expense.', 'Новые тараны и башни готовы; {king} хочет испытать их остриё в живом учении — расход нелёгкий.', '新造の破城車と雲梯が揃い、{king}はその切れ味を実戦演習で試したい——費用は軽くない。', 'Neue Rammböcke und Türme stehen bereit; {king} will ihre Schärfe in einer Übung prüfen — kein leichter Aufwand.'),
 q('实兵试车', '實兵試車', 'Run the trial', 'Провести испытание', '実地試験', 'Probe abhalten'),
 q('筑土城、调精卒试新械，试罢或成良法。', '築土城、調精卒試新械，試罷或成良法。', 'Raise a mock wall and set elite troops to test the engines; a sound method may follow.', 'Поставить ложную стену и дать отборным испытать машины; может родиться дельный способ.', '土塁を築き精鋭に新兵器を試させれば、良い術が生まれるかもしれぬ。', 'Eine Scheinmauer werfen und Elitetruppen die Maschinen testen lassen; vielleicht entsteht ein gutes Verfahren.'),
 q('器械利钝尽知，攻守之术日精；金帛亦随之耗。', '器械利鈍盡知，攻守之術日精；金帛亦隨之耗。', 'The worth of every engine is known and siegecraft sharpens; gold and silk burn with it.', 'Цена машин узнана, осадное дело острее; золото и шёлк горят вместе с ним.', '利器の良否は明らかになり攻防の術が磨かれる——金も共に燃えた。', 'Der Wert jeder Maschine ist bekannt, die Belagerungskunst schärft sich; Gold und Seide verbrennen mit.'),
 q('虚应故事', '虛應故事', 'A hollow review', 'Показной смотр', '形ばかりの検分', 'Hohle Musterung'),
 q('仅空阅其械，未试利于城下。', '僅空閱其械，未試利於城下。', 'Merely parade the machines, never trying them beneath the walls.', 'Лишь проехать с машинами, не испытав их у стен.', '兵器を並べるだけで、城下での試しはしない。', 'Nur das Gerät vorführen, es nie unter der Mauer erproben.'),
 q('利器束之高阁，攻术依旧，虚耗一场。', '利器束之高閣，攻術依舊，虛耗一場。', 'The engines gather dust, siegecraft stands still, and the affair is wasted.', 'Машины пылятся, осадное дело стоит, затея впустую.', '利器は棚上げ、攻城術は旧態依然——無駄な一席だった。', 'Die Maschinen verstauben, die Kunst steht still, das Ganze war verloren.')
)
ev('scout_failure', 2,
 ('斥候失察', '斥候失察', 'The Scout\'s Failure', 'Провал разведки', '斥候の失態', 'Des Kundschafters Fehler'),
 ('哨探误报军情，一军错行战机，丧师数百人。{king}须究其责。', '哨探誤報軍情，一軍錯行戰機，喪師數百人。{king}須究其責。', 'A scout misreports; a host misses its chance at victory and loses hundreds. {king} must weigh the blame.', 'Лазутчик ошибся в донесении; войско упустило шанс и потеряло сотни. {king} должен взвесить вину.', '斥候が軍情を誤り、一軍は好機を逃して数百を失った。{king}は責を問わねばならぬ。', 'Ein Späher meldet falsch; ein Heer verspielt die Chance und verliert Hunderte. {king} muss die Schuld wägen.'),
 q('斩首儆众', '斬首儆眾', 'Behead to warn', 'Казнить для острастки', '斬首で戒める', 'Enthaupten zur Warnung'),
 q('斩斥候主官以肃军纪，诸军悚然，然怨亦生。', '斬斥候主官以肅軍紀，諸軍悚然，然怨亦生。', 'Execute the scout-chief to restore discipline; the ranks quail, yet grudges are born.', 'Казнить старшего разведчика; ряды трепещут, но обиды рождаются.', '斥候の長を斬って軍紀を正せば、諸軍は恐れるが恨みも生まれる。', 'Den Spähermeister hinrichten, die Zucht herstellen; die Ränge erbeben, doch der Groll wird geboren.'),
 q('军纪复肃，然军中暗传其冤，人心微沮。', '軍紀復肅，然軍中暗傳其冤，人心微沮。', 'Discipline recovers, but whispers of injustice dampen the hearts of the host.', 'Дисциплина вернулась, но шёпот о несправедливости давит на сердца.', '軍紀は戻るが、無実の噂が心を沈ませる。', 'Die Zucht kehrt zurück, doch Flüstern von Unrecht drückt die Herzen.'),
 q('轻责杖罚', '輕責杖罰', 'A light rod', 'Лёгкая порка', '鞭打ちで済ます', 'Eine leichte Rute'),
 q('杖其首领，免其死罪，众皆掩口。', '杖其首領，免其死罪，眾皆掩口。', 'Flog the leader and spare his life; the host falls into guarded silence.', 'Порка начальнику, жизнь сохранена; войско хранит молчание.', '長を鞭打ち死罪は免れれば、兵は口を噤む。', 'Den Führer stäupen, das Leben schonen; das Heer verstummt hütend.'),
 q('斥候得全，军心略安；然失机之痛未消。', '斥候得全，軍心略安；然失機之痛未消。', 'The scout lives and hearts ease a little, yet the ache of the lost chance endures.', 'Лазутчик жив, сердца чуть легче; но боль упущенного шанса жива.', '斥候は生き延び軍心は少し安んじる——失われた機会の痛みは残る。', 'Der Kundschafter lebt, die Herzen leichten sich; doch der Schmerz der verlorenen Chance bleibt.')
)
ev('navy_draft', 2,
 ('水师之召', '水師之召', 'The Navy Draft', 'Набор во флот', '水軍の募集', 'Die Flottenaushebung'),
 ('海疆不靖，水师须广募水手船匠。{king}或厚赏募之，或强征之。', '海疆不靖，水師須廣募水手船匠。{king}或厚賞募之，或強徵之。', 'The coast is restless; the fleet must recruit sailors and shipwrights. {king} may hire them richly or press them.', 'Побережье неспокойно; флоту нужны матросы и корабельщики. {king} может щедро нанять или принуждать.', '海が騒がしい——水軍には水夫と船大工が要る。{king}は金で募るか、強制徴発するか。', 'Die Küste ist rastlos; die Flotte braucht Matrosen und Werftleute. {king} kann reichlich werben oder pressen.'),
 q('厚赏募勇', '厚賞募勇', 'Hire with bounty', 'Нанять за награду', '金で募る', 'Mit Prämien werben'),
 q('出重金募积年水手，工料募费不赀。', '出重金募積年水手，工料募費不貲。', 'Pay heavily for seasoned sailors; the cost of craft and recruiting is no trifle.', 'Щедро платить бывалым морякам; цена снаряжения и набора не мелочь.', '年季の水夫に手厚い金を出せば、資材と募集の出費も軽くない。', 'Reichlich für erprobte Matrosen zahlen; der Preis für Gerät und Werbung ist kein Pappenstiel.'),
 q('水师成军，帆樯林立；金库渐露窘色。', '水師成軍，帆檣林立；金庫漸露窘色。', 'The fleet stands, masts like a forest; the treasury begins to show its straits.', 'Флот стоит, мачты как лес; казна начинает показывать нужду.', '水軍は立ち上がり帆桁が森のよう——国庫は次第に苦しくなる。', 'Die Flotte steht, Masten wie ein Wald; die Kasse zeigt allmählich ihre Not.'),
 q('强征船户', '強徵船戶', 'Press the fishers', 'Принудить рыбаков', '船戸を強制する', 'Die Fischer pressen'),
 q('尽括沿海船户以充水籍，怨声载道。', '盡括沿海船戶以充水籍，怨聲載道。', 'Enroll every coastal household into the navy rolls; the outcry fills the roads.', 'Записать все прибрежные дома во флотские списки; вопль полнит дороги.', '沿海の家々を無理やり水軍の名簿に編入すれば、怨みが道に溢れる。', 'Alle Küstenhäuser in die Flottenlisten schreiben; das Geschrei füllt die Wege.'),
 q('渔村萧条，船户结怨，新卒怨而操练废弛。', '漁村蕭條，船戶結怨，新卒怨而操練廢弛。', 'Fishing villages decay, the households nurse grudges, and the recruits drill sullenly.', 'Рыбацкие сёла увядают, дома копят обиды, новобранцы учатся угрюмо.', '漁村は寂れ、船戸は怨みを抱え、新兵は怒りながら訓練も手を抜く。', 'Fischerdörfer verwelken, die Häuser hegen Groll, die Neuen exerzieren verdrossen.')
)
ev('camp_disease', 2,
 ('营疫流行', '營疫流行', 'Sickness in Camp', 'Болезнь в лагере', '陣中の疫病', 'Seuche im Lager'),
 ('军中疫气大作，日有倒毙。大医求药于{king}，须千金以购之。', '軍中疫氣大作，日有倒斃。大醫求藥於{king}，須千金以購之。', 'Plague stalks the host and men fall daily. The physicians beg medicine of {king} — it costs a thousand in gold.', 'Мор косит войско, люди падают ежедневно. Врачи просят лекарств у {king} — это стоит тысячу золота.', '軍中に疫病が猛り毎日人が倒れる。医師が{king}に薬を求める——千金を要する。', 'Die Pest streift das Heer, täglich fallen Männer. Die Ärzte bitten {king} um Arznei — sie kostet tausend Gold.'),
 q('购药施治', '購藥施治', 'Buy the cures', 'Купить снадобья', '薬を買う', 'Heilmittel kaufen'),
 q('出重金采买药材，设方药局煎剂分治。', '出重金採買藥材，設方藥局煎劑分治。', 'Pay dear for herbs and open an apothecary to brew and tend the sick.', 'Щедро платить за травы и открыть аптеку для отваров и ухода.', '金を出して生薬を買い、薬局を設けて煎じて分け与える。', 'Teuer für Kräuter zahlen und eine Apotheke eröffnen, zu sieden und zu pflegen.'),
 q('疫气渐敛，士卒复振；药资则一大耗费。', '疫氣漸斂，士卒復振；藥資則一大耗費。', 'The pestilence recedes and the host revives; the remedy bill is a heavy charge.', 'Мор отступает, войско оживает; счёт за лекарства — тяжёлый расход.', '疫気は治まり兵は元気を取り戻す——薬代は大きな出費だった。', 'Die Seuche weicht, das Heer erholt sich; die Rechnung für Arznei ist eine schwere Last.'),
 q('听天由命', '聽天由命', 'Let fate carry', 'Пустить на волю судьбы', '天命に任す', 'Dem Schicksal vertrauen'),
 q('只焚艾草令其自愈，营中尸气难掩。', '只焚艾草令其自愈，營中屍氣難掩。', 'Burn only mugwort and let men mend themselves; the smell of the dead is everywhere.', 'Жечь лишь полынь и оставить людей поправляться; запах мёртвых повсюду.', '艾草を焚くだけで自らの治癒に任せれば、陣中の死臭を隠せない。', 'Nur Beifuß brennen und die Männer sich selbst heilen lassen; der Gestank der Toten ist überall.'),
 q('疫势蔓延，营伍减员，战力大挫。', '疫勢蔓延，營伍減員，戰力大挫。', 'The plague spreads, ranks dwindle, and fighting strength takes a heavy blow.', 'Мор расползается, ряды редеют, боевая сила получает тяжкий удар.', '疫病は広がり隊列は痩せ、戦力は大きな打撃を受けた。', 'Die Seuche greift um sich, die Reihen schwinden, die Schlagkraft erleidet einen schweren Stoß.')
)
ev('weapon_bribe', 2,
 ('军械贿赂', '軍械賄賂', 'The Weapons Bribe', 'Взятка за оружие', '武器の賄賂', 'Die Waffenbestechung'),
 ('军需官私通奸商，以劣充优。{king}查有实据，须断此案以正军心。', '軍需官私通奸商，以劣充優。{king}查有實據，須斷此案以正軍心。', 'A quartermaster colludes with a rogue trader and passes off shoddy steel. {king} holds the proof and must judge it.', 'Интендант в сговоре с жуликоватым торговцем выдает скверную сталь за добрую. Улики в руках {king}, и он должен судить.', '軍需官が悪徳商人と結託し粗悪品を良品に偽る。証拠は{king}の手にあり、裁断が必要だ。', 'Ein Quartiermeister tut sich mit einem Schurkenhändler zusammen und schiebt schäbigen Stahl durch. {king} hält den Beweis und muss richten.'),
 q('明正典刑', '明正典刑', 'Try him by law', 'Судить по закону', '王法で裁く', 'Nach Gesetz richten'),
 q('拿问军需官，追赃问罪，军中肃然。', '拿問軍需官，追贓問罪，軍中肅然。', 'Arrest the quartermaster and recover the stolen goods; the host stands in awe.', 'Арестовать интенданта и вернуть украденное; войско в благоговении.', '軍需官を捕えて不正を追及すれば、軍中は粛然とする。', 'Den Quartiermeister festsetzen, die Beute zurückfordern; das Heer steht in Ehrfurcht.'),
 q('贪墨一清，然勾连者众多，借机攻讦者四起。', '貪墨一清，然勾連者眾多，藉機攻訐者四起。', 'The graft is swept clean, yet many are entangled, and denunciations flare on every side.', 'Мзда выметена, но запутанных много, и доносы вспыхивают со всех сторон.', '汚職は一掃されたが、連座者が多く弾劾合戦が四方に起きた。', 'Die Bestechung ist gefegt, doch viele sind verstrickt, und Denunziationen flammen von allen Seiten.'),
 q('罚酒三杯', '罰酒三杯', 'Let it pass', 'Закрыть глаза', '罰金で済ませる', 'Durchgehen lassen'),
 q('薄责了案，暂且遮掩，奸商欢笑如故。', '薄責了案，暫且遮掩，奸商歡笑如故。', 'Rebuke lightly and cover it over; the rogue trader laughs as before.', 'Легко пожурить и замять; жулик смеётся как прежде.', '軽く叱って闇に葬れば、悪徳商人は相変わらず笑う。', 'Leicht rügen und vertuschen; der Schurke lacht wie zuvor.'),
 q('劣械依旧入库，军心暗寒，怨声渐积。', '劣械依舊入庫，軍心暗寒，怨聲漸積。', 'Shoddy gear still enters the stores; the army grows cold inside and resentment piles up.', 'Скверное снаряжение всё ещё входит в склады; армия холодеет, обиды копятся.', '粗悪品は依然倉庫に入り、軍の心は冷えて怨みが積もる。', 'Minderes Gerät kommt weiterhin in die Magazine; das Heer erkaltet innerlich, der Groll stapelt sich.')
)
ev('royal_guard_move', 2,
 ('禁军移防', '禁軍移防', 'The Guard Relocation', 'Перевод гвардии', '禁軍の移駐', 'Die Garde verlegt'),
 ('王城禁军久戍京畿，日久沉湎逸乐。{king}欲移营郊外大操重训。', '王城禁軍久戍京畿，日久沉湎逸樂。{king}欲移營郊外大操重訓。', 'The royal guard has long sat about the capital, sunk in ease. {king} would move them out and drill them hard.', 'Дворцовая гвардия засиделась у столицы, утопая в досуге. {king} хочет вывести её и переучить всерьёз.', '王都の禁軍は長く城に居て安逸に浸る。{king}は郊外へ移して厳しく鍛え直したい。', 'Die Garde hält sich lange in der Hauptstadt, versunken in Muße. {king} will sie hinauslegen und hart drillen.'),
 q('移营重训', '移營重訓', 'Move & retrain', 'Вывести и учить', '移して再訓練', 'Verlegen & drillen'),
 q('发帑出城安营，重立戒律，操习劳之。', '發帑出城安營，重立戒律，操習勞之。', 'Fund an outpost beyond the walls, restate the rules, and weary the men with drill.', 'Оплатить лагерь за стенами, повторить устав и утомить ученьем.', '金を出し城外に陣を張り、戒律を立て直して酷練で疲れさせる。', 'Ein Lager jenseits der Mauern bezahlen, die Ordnung erneuern, die Männer mit Exerzieren mühen.'),
 q('禁军筋骨复壮，拱卫愈固；费亦可观。', '禁軍筋骨復壯，拱衛愈固；費亦可觀。', 'The guard regains sinew and stands firmer; the outlay is considerable.', 'Гвардия набирает силу и стоит крепче; расход значителен.', '禁軍の筋骨は蘇り警衛は固まる——費用もそれ相応だ。', 'Die Garde gewinnt Kraft und steht fester; der Aufwand ist beträchtlich.'),
 q('且留京中', '且留京中', 'Leave them be', 'Оставить как есть', '京に残す', 'Sie bleiben lassen'),
 q('念其劳苦，仍留城中，不兴调动。', '念其勞苦，仍留城中，不興調動。', 'Pity their toil and keep them in the city; no move is made.', 'Пожалеть их труды и оставить в городе; никакого перевода.', '労苦を思いやり城中に留め、移駐は行わない。', 'Ihre Arbeit beklagen und sie in der Stadt lassen; keine Verlegung.'),
 q('禁军如常拱卫，未生新事，亦未增其锐。', '禁軍如常拱衛，未生新事，亦未增其銳。', 'The guard keeps its post as ever — no new incidents, and no new edge either.', 'Гвардия стоит как всегда — ни новых происшествий, ни нового острия.', '禁軍は従来どおり警衛——新しい風波も鋭さもない。', 'Die Garde hält ihren Posten wie eh — keine neuen Vorfälle, keine neue Schärfe.')
)
ev('desertion', 2,
 ('士卒之逃', '士卒之逃', 'The Desertion', 'Дезертирство', '士卒の逃亡', 'Die Fahnenflucht'),
 ('战云压城，一夜之间数百卒籍者聚奔于野。{king}须止此逃风。', '戰雲壓城，一夜之間數百卒籍者聚奔於野。{king}須止此逃風。', 'War clouds press on the city; in one night hundreds of the rolls slip away together. {king} must stop the flight.', 'Война сгущается; за одну ночь сотни из списков уходят прочь разом. {king} должен остановить побег.', '戦雲が城を圧し、一夜で名簿の数百人がまとまって逃げた。{king}は逃亡の風を止めねばならぬ。', 'Kriegswolken drücken die Stadt; in einer Nacht schlüpfen Hunderte von den Listen zusammen davon. {king} muss das Fliehen stoppen.'),
 q('榜告连坐', '榜告連坐', 'Decrees & kinship', 'Указ и порука', '連座の令', 'Erlass & Sippe'),
 q('捕逃者杖以儆众，株连邻里，逃风暂止。', '捕逃者杖以儆眾，株連鄰里，逃風暫止。', 'Flog the captured as a warning and implicate their neighbors; the flight pauses a while.', 'Пороть пойманных для острастки и задевать соседей; побег замирает на время.', '捕えた者を鞭打ち隣里にも及ぼせば、逃亡は一時止まる。', 'Die Gefangenen zur Warnung stäupen und die Nachbarn hineinziehen; das Fliehen stockt eine Weile.'),
 q('逃卒就擒，然刑威之下乡怨沸腾。', '逃卒就擒，然刑威之下鄉怨沸騰。', 'The runaways are seized, yet village fury boils beneath the rod.', 'Беглецов хватают, но гнев деревень кипит под розгами.', '逃兵は捕らえられたが、鞭の下で村の怨みが沸騰する。', 'Die Flüchtlinge werden gegriffen, doch der Dorfzorn siedet unter der Rute.'),
 q('召还抚谕', '召還撫諭', 'Recall & pardon', 'Вернуть и простить', '呼び戻し許す', 'Zurückrufen & verzeihen'),
 q('许其归营不罪，给饷安家，费帑数千。', '許其歸營不罪，給餉安家，費帑數千。', 'Promise return without punishment and wages for their homes; it costs silver by the thousand.', 'Пообещать возврат без кары и жалование домам; это стоит серебра тысячами.', '罪を問わず帰営を許し、家に給金を渡せば費用は数千に及ぶ。', 'Heimkehr ohne Strafe und Sold für die Häuser versprechen; es kostet Silber zu Tausenden.'),
 q('逃者半返，军心略定；金帛随之耗。', '逃者半返，軍心略定；金帛隨之耗。', 'Half the runaways return; the army steadies a little, and gold and silk drain away with them.', 'Половина беглецов вернулась; армия чуть крепнет, и золото со шёлком утекают.', '逃げた者の半数が戻り、軍心は少し安定——金と帛が共に減る。', 'Die Hälfte kehrt zurück; das Heer festigt sich ein wenig, Gold und Seide rinnen mit davon.')
)
ev('war_plunder_share', 2,
 ('战利均分', '戰利均分', 'Sharing the Plunder', 'Раздел добычи', '戦利品の分配', 'Die Beute teilen'),
 ('攻破敌城，辎重山积。{king}或均分三军以结其心，或尽收王库。', '攻破敵城，輜重山積。{king}或均分三軍以結其心，或盡收王庫。', 'The enemy city falls; the baggage is mountainous. {king} may share it among the host, or gather it all into the treasury.', 'Город пал; обозы горой. {king} может разделить между войском или свести всё в казну.', '敵の城が落ち、兵站物資が山と積まれる。{king}は三軍に分け与えるか、全て国庫に収めるか。', 'Die feindliche Stadt fällt; der Tross liegt wie ein Berg. {king} kann an das Heer teilen oder alles in die Kasse ziehen.'),
 q('三军均分', '三軍均分', 'Share to all', 'Разделить всем', '全軍に分ける', 'Allen teilen'),
 q('尽分战利，自伍长至士卒皆有恩赏。', '盡分戰利，自伍長至士卒皆有恩賞。', 'Divide the whole of the spoils, from sergeants to the common soldier; every man is rewarded.', 'Поделить всю добычу, от сержантов до простых солдат; всякий награждён.', '伍長から士卒まで全員に行き渡るように戦利品を分ける。', 'Die ganze Beute teilen, vom Wachtmeister bis zum gemeinen Soldaten; jeder wird belohnt.'),
 q('三军欢呼，列国称{kingdom}厚待士卒，军心大固。', '三軍歡呼，列國稱{kingdom}厚待士卒，軍心大固。', 'The host roars; realms praise {kingdom} for cherishing its soldiers, and hearts stand firm.', 'Войско ликует; соседи хвалят {kingdom} за заботу о солдатах, сердца стоят крепко.', '三軍は歓呼し、諸国は{kingdom}の厚情を讃え軍心は大いに固まる。', 'Das Heer jubelt; Reiche preisen {kingdom} für die Sorge um die Soldaten, die Herzen stehen fest.'),
 q('尽收王库', '盡收王庫', 'Hoard at court', 'Прятать при дворе', 'すべて国庫へ', 'Am Hofe horten'),
 q('辎重输入王库，士卒空手而不平。', '輜重輸入王庫，士卒空手而不平。', 'Haul the baggage into the treasury; the men walk off empty-handed and aggrieved.', 'Свести обозы в хранилище; люди уходят с пустыми руками и обидой.', '戦利品をすべて国庫に運べば、兵は手ぶらで不満を抱く。', 'Den Tross ins Gewölbe ziehen; die Männer gehen leer und gekränkt davon.'),
 q('库帑丰矣，而军中怨言四起，哗变险生。', '庫帑豐矣，而軍中怨言四起，譁變險生。', 'The treasury grows rich, but resentment rises through the host and mutiny nearly breaks.', 'Казна богатеет, но ропот растёт по войску, и мятеж вот-вот прорвётся.', '国庫は潤ったが陣中に怨言が渦巻き、叛乱が今にも起きそうだ。', 'Die Kasse wird reich, doch der Groll steigt durchs Heer, und die Meuterei will fast brechen.')
)
ev('general_young', 2,
 ('少将之拜', '少將之拜', 'The Young General', 'Молодой генерал', '若き将の抜擢', 'Der junge Feldherr'),
 ('少年将军屡建奇功，诸将皆耸动。{king}欲破格拜其为大都护。', '少年將軍屢建奇功，諸將皆聳動。{king}欲破格拜其為大都護。', 'A stripling commander keeps winning wonders; the generals are startled. {king} would break precedent and raise him high.', 'Юный вождь творит чудеса; генералы изумлены. {king} хочет нарушить обычай и возвысить его.', '若き将が奇功を連ね、諸将が騒ぐ。{king}は破格に大都護に拝したい。', 'Ein Knabe in Waffen siegt immer wieder; die Generäle erschrecken. {king} will den Brauch brechen und ihn hochheben.'),
 q('破格拜将', '破格拜將', 'Raise him high', 'Возвысить', '破格に拝する', 'Hochheben'),
 q('越级拜为大将，以励来者，旧将侧目。', '越級拜為大將，以勵來者，舊將側目。', 'Promote him above the roster to spur the rest; the old generals look askance.', 'Возвысить через список, чтобы вдохновить прочих; старые генералы косятся.', '序列を越えて大将にし後進を励ませば、老将は苦い顔をする。', 'Ihn über die Liste hinaus befördern, um die übrigen zu stacheln; die alten Generäle blicken scheel.'),
 q('少将拜印，列国称{kingdom}用人唯才，军中新锐奋起。', '少將拜印，列國稱{kingdom}用人唯才，軍中新銳奮起。', 'He takes the seal; realms praise merit alone in {kingdom}, and the young in arms are roused.', 'Он получает печать; соседи славят одну лишь заслугу в {kingdom}, молодые воины вдохновлены.', '若将は印を拝し、諸国は{kingdom}の才登用を讃え、若き兵士が奮い立つ。', 'Er empfängt das Siegel; Reiche rühmen allein das Verdienst in {kingdom}, die jungen Soldaten springen auf.'),
 q('循资授职', '循資授職', 'Follow seniority', 'По старшинству', '年功のまま', 'Der Rangliste folgen'),
 q('仅循资序授职，少年将默然受之。', '僅循資序授職，少年將默然受之。', 'Advance him by the ladder of seniority alone; the stripling accepts in silence.', 'Продвинуть лишь по списку старшинства; юнец принимает молча.', '年功の順だけでの授職なら、若将は黙って受け入れる。', 'Nur nach der Stufenleiter des Dienstalters befördern; der Knabe nimmt es schweigend.'),
 q('老将颔首，少年怅然，军中暂归于静。', '老將頷首，少年悵然，軍中暫歸於靜。', 'The veterans nod, the youth is downcast, and the host settles into stillness.', 'Ветераны кивают, юноша уныл, войско замирает в тишине.', '老将は頷き、若将は悄然——陣中はしばし静けさに戻る。', 'Die Veteranen nicken, der Junge ist bedrückt, das Heer sinkt in Stille.')
)
ev('fort_novelty', 2,
 ('新法筑垒', '新法築壘', 'The Novel Fort', 'Новая крепость', '新式の砦', 'Die neuartige Festung'),
 ('有巧匠献新式棱堡之图。{king}欲命筑一城试其利否，工费浩大。', '有巧匠獻新式稜堡之圖。{king}欲命築一城試其利否，工費浩大。', 'A cunning craftsman offers a drawing of a novel star-fort. {king} would raise one city to test it — the works will be enormous.', 'Хитрый мастер подаёт чертёж новой звездообразной крепости. {king} хочет поднять одну для пробы — работы огромны.', '名工が新式の稜堡の設計図を献上する。{king}は試しに一城を築くか——工費は莫大だ。', 'Ein schlauer Meister legt den Plan einer neuen Sternschanze vor. {king} will eine Stadt bauen, um sie zu prüfen — die Werke werden gewaltig.'),
 q('筑堡以试', '築堡以試', 'Build to test', 'Построить для пробы', '築いて試す', 'Probeweise bauen'),
 q('出金开土筑基，依新法筑之，费时费力。', '出金開土筑基，依新法築之，費時費力。', 'Spend gold, break the ground, and raise the fort by the new method; it takes time and toil.', 'Дать золото, вскрыть землю и возвести крепость по-новому; это время и труд.', '金を出して土地を掘り、新工法で築けば、時間と労力が要る。', 'Gold geben, den Boden brechen, nach neuem Verfahren bauen; es kostet Zeit und Mühe.'),
 q('堡成势壮，攻守俱便；然工费沉重。', '堡成勢壯，攻守俱便；然工費沉重。', 'The fort stands imposing, fair for both attack and defense; the works are heavy indeed.', 'Крепость стоит внушительно, мощна и в обороне, и в осаде; работы тяжелы.', '砦は堅牢で攻守に便なり——工費もまた重い。', 'Die Festung steht stattlich, gut für Angriff wie Verteidigung; die Werke sind schwer.'),
 q('留图不筑', '留圖不築', 'Keep the plan', 'Оставить чертёж', '図を眺めて仕舞う', 'Den Plan verwahren'),
 q('览图称善而藏之，不兴土役。', '覽圖稱善而藏之，不興土役。', 'Praise the drawing, then store it away; no earth is stirred.', 'Похвалить чертёж и спрятать; земля не шелохнётся.', '図を褒めて蔵に仕舞い、土工は起こさない。', 'Die Zeichnung loben und weglegen; keine Erde wird bewegt.'),
 q('新图藏于库中，旧垒依旧，未害未益。', '新圖藏於庫中，舊壘依舊，未害未益。', 'The new drawing sleeps in the archive; the old walls stand — neither harmed nor helped.', 'Новый чертёж спит в архиве; старые стены стоят — ни вреда, ни пользы.', '新図は倉庫に眠り、旧城は健在——益も害もない。', 'Die neue Zeichnung schläft im Archiv; die alten Mauern stehen — weder Schaden noch Nutzen.')
)
ev('outpost_security', 2,
 ('前哨之备', '前哨之備', 'The Outpost\'s Guard', 'Стража передового поста', '前哨の備え', 'Die Wache des Vorpostens'),
 ('边外前哨孤立，粮道时断。{king}欲添兵增垒以稳之，费不赀。', '邊外前哨孤立，糧道時斷。{king}欲添兵增壘以穩之，費不貲。', 'The outpost beyond the border stands alone; its supply road is often cut. {king} would add men and walls — no mean expense.', 'Передовой пост за границей одинок; его дорога часто перерезана. {king} хочет прибавить людей и стены — расход немалый.', '国境の前哨は孤立し、兵站の道はしばしば断たれる。{king}は兵と砦を増やして固めたい——費用は多くかかる。', 'Der Vorposten jenseits der Grenze steht allein; seine Versorgungsstraße wird oft abgeschnitten. {king} will Männer und Mauern mehren — kein geringer Aufwand.'),
 q('添兵固垒', '添兵固壘', 'Reinforce & fortify', 'Укрепить и усилить', '兵を増し砦を固める', 'Verstärken & befestigen'),
 q('增哨兵、修栈道，前哨遂安，耗费亦钜。', '增哨兵、修棧道，前哨遂安，耗費亦鉅。', 'Add sentries and mend the plank road; the outpost rests easy, and the spending is heavy.', 'Прибавить дозорных и починить мостовую; пост покоен, расход тяжек.', '哨兵を増やし道を直せば前哨は安らぐ——費用もかかる。', 'Wachen mehren und die Holzstraße flicken; der Posten ruht, die Ausgabe ist schwer.'),
 q('哨道畅通，烽息无警；金帛则耗于砖石。', '哨道暢通，烽息無警；金帛則耗於磚石。', 'The watch runs clear and no beacon burns; gold and silk have gone into stone.', 'Дорога ясна, маяки молчат; золото и шёлк ушли в камень.', '哨路は通じ烽火も静か——金と帛は石に化けた。', 'Die Wache läuft klar, kein Zeichen brennt; Gold und Seide gingen in Stein.'),
 q('不予置理', '不予置理', 'Let it be', 'Оставить его', 'そのままにする', 'Ihn lassen'),
 q('前哨依旧受敌之扰，险象环生。', '前哨依舊受敵之擾，險象環生。', 'The outpost stays harried by enemies; peril flashes on every side.', 'Пост остаётся под ударами врагов; опасность мелькает отовсюду.', '前哨は敵の妨害のまま——危険が次々と現れる。', 'Der Posten bleibt vom Feind bedrängt; Gefahr blitzt von allen Seiten auf.'),
 q('前哨仍孤悬，时有惊报，所幸尚无大失。', '前哨仍孤懸，時有驚報，所幸尚無大失。', 'The outpost hangs alone with alarms from time to time; luckily, no great loss as yet.', 'Пост всё ещё висит одиноко, тревоги приходят; к счастью, пока без потерь.', '前哨は孤軍のまま、時折りの警報——幸いまだ大損はない。', 'Der Posten hängt allein, Alarm von Zeit zu Zeit; zum Glück noch kein großer Verlust.')
)
ev('wounded_care', 2,
 ('伤兵之医', '傷兵之醫', 'The Wounded\'s Care', 'Забота о раненых', '傷兵の看護', 'Die Pflege der Verwundeten'),
 ('每战之后，伤兵载道。医护与药品皆缺，{king}当拨帑救治否。', '每戰之後，傷兵載道。醫護與藥品皆缺，{king}當撥帑救治否。', 'After every battle the wounded fill the roads; healers and medicine run short. Will {king} spend to save them?', 'После каждой битвы дороги полны раненых; лекарей и лекарств нет. Потратит ли {king} деньги на спасение?', '戦のたびに負傷兵が道に溢れ、医師も薬も足りぬ。{king}は金を出して救うべきか。', 'Nach jeder Schlacht füllen Verwundete die Wege; Heiler und Arznei gehen aus. Gibt {king} Geld, sie zu retten?'),
 q('拨帑救治', '撥帑救治', 'Spend on healing', 'Потратить на лечение', '金を出して治療', 'Für Heilung zahlen'),
 q('设伤兵院、广购汤药，以全其生。', '設傷兵院、廣購湯藥，以全其生。', 'Found a hospital and buy medicines in quantity to save their lives.', 'Открыть лазарет и закупить лекарства оптом ради жизней.', '傷兵院を設け薬をまとめ買いし、命を守らせる。', 'Ein Lazarett stiften und Arznei in Menge kaufen, um das Leben zu retten.'),
 q('伤兵多愈，军心感奋；内帑为之一轻。', '傷兵多癒，軍心感奮；內帑為之一輕。', 'Many of the wounded recover; the host is moved — and the inner treasury grows lighter.', 'Многие встают; войско тронуто — внутренняя казна полегчала.', '多くは癒え軍心は奮い立つ——内庫はぐっと軽くなった。', 'Viele genesen; das Heer ist ergriffen — die innere Kasse wird leichter.'),
 q('任其自生', '任其自生', 'Let them wither', 'Оставить чахнуть', 'そのまま放置', 'Sie darben lassen'),
 q('谕医者先救贵官，伤卒多半转痿。', '諭醫者先救貴官，傷卒多半轉痿。', 'Bid the healers tend the officers first; common wounded mostly pine away.', 'Велеть врачам сперва лечить офицеров; простые раненые чахнут.', '医者に高官を先に看よと言えば、下卒は次々と痩せ衰える。', 'Den Ärzten heißen, erst die Offiziere zu pflegen; die gemeinen Verwundeten siechen dahin.'),
 q('伤卒凋零，营中寒心，怨声渐起。', '傷卒凋零，營中寒心，怨聲漸起。', 'The wounded die off; the camps grow cold and voices of complaint rise.', 'Раненые вымирают; лагеря холодеют, голоса растут.', '傷兵は斃れ、陣中は冷え、怨みの声が高まる。', 'Die Verwundeten sterben weg; die Lager erkalten, Klagen erheben sich.')
)
ev('hero_statue', 2,
 ('英雄之像', '英雄之像', 'The Hero\'s Statue', 'Статуя героя', '英雄の像', 'Das Standbild des Helden'),
 ('阵亡名将功在社稷，易名勒石犹不足，{king}欲铸铜像以旌之。', '陣亡名將功在社稷，易名勒石猶不足，{king}欲鑄銅像以旌之。', 'A fallen general served the realm; names on stone are not enough. {king} would cast him in bronze to honor him.', 'Павший генерал служил державе; имён на камне мало. {king} хочет отлить его в бронзе для славы.', '戦死した名将は国に功あり、石に名を刻むだけでは足りぬ——{king}は銅像を建てて顕彰したい。', 'Ein gefallener General diente dem Reich; Namen auf Stein genügen nicht. {king} will ihn in Erz gießen, um ihn zu ehren.'),
 q('铸像旌表', '鑄像旌表', 'Cast the statue', 'Отлить статую', '銅像を建てる', 'Erz gießen'),
 q('聚铜铸像，立于通衢，费帑数千。', '聚銅鑄像，立於通衢，費帑數千。', 'Gather copper for a statue to stand on the high road; it drains silver by the thousand.', 'Собрать медь для статуи на большой дороге; эта трата тысячи серебра.', '銅を集め大通りに像を建てれば、銀が数千を要する。', 'Kupfer für ein Standbild auf der Heerstraße sammeln; es zehrt an Silber zu Tausenden.'),
 q('铜像巍然，三军思奋；金库亦少一截。', '銅像巍然，三軍思奮；金庫亦少一截。', 'The bronze stands tall and the host stirs to valor; the treasury is shorter by a length.', 'Бронза стоит высоко, войско рвётся к доблести; казна короче на целый рост.', '青銅の像は高く立ち、三軍は奮い立つ——国庫も一段縮んだ。', 'Das Erz steht hoch, das Heer regt sich zur Tapferkeit; die Kasse ist um eine Länge kürzer.'),
 q('刻石传铭', '刻石傳銘', 'Engrave a stela', 'Высечь стелу', '碑を刻む', 'Eine Stele meißeln'),
 q('勒石立碑记其功，工简费省。', '勒石立碑記其功，工簡費省。', 'Cut a stela recording his deeds; the work is simple and the cost light.', 'Высечь стелу с записью дел; труд прост, цена мала.', '功績を碑に刻めば、工はささやかで費用も軽い。', 'Eine Stele mit den Taten meißeln; die Arbeit ist einfach, der Preis gering.'),
 q('民众传诵其忠，列国称{kingdom}崇德有度。', '民眾傳誦其忠，列國稱{kingdom}崇德有度。', 'The people retell his loyalty; realms praise {kingdom} for honoring virtue with measure.', 'Люди пересказывают его верность; соседи хвалят {kingdom} за честь добродетели с мерой.', '民はその忠を謳い、諸国は{kingdom}の徳を尊ぶ節度を讃えた。', 'Das Volk erzählt seine Treue; Reiche loben {kingdom} für ein gemessenes Ehren der Tugend.')
)
ev('land_grant_soldier', 2,
 ('军功授田', '軍功授田', 'Land to Veterans', 'Земля ветеранам', '軍功への土地', 'Land für Veteranen'),
 ('百战之卒，解甲乡野无所归。{king}欲授田赐爵，以安其晚年。', '百戰之卒，解甲鄉野無所歸。{king}欲授田賜爵，以安其晚年。', 'Soldiers of a hundred battles leave the ranks with nowhere to go. {king} would grant them fields and rank to ease their age.', 'Солдаты ста битв уходят из строя без пристанища. {king} хочет даровать им поля и звания для спокойной старости.', '百戦の兵は解き放たれ行く先がない。{king}は功に応じ田と爵を授けて老後を安んじさせたい。', 'Kämpfer von hundert Schlachten verlassen die Ränge ohne Ziel. {king} will Felder und Rang gewähren, ihr Alter zu sichern.'),
 q('授田赐爵', '授田賜爵', 'Grant land & rank', 'Дать землю и звание', '田と爵を授ける', 'Land & Rang vergeben'),
 q('按功授田、给爵，费帑虽钜而恩深。', '按功授田、給爵，費帑雖鉅而恩深。', 'Award fields by merit and titles besides; the outlay is great but the grace is deep.', 'Наградить полями по заслугам и титулами сверх; расход велик, но милость глубока.', '功に応じ田を分け爵位も添えれば、出費は多いが恩は深い。', 'Felder nach Verdienst und Titel obendrein; der Aufwand ist groß, die Gnade tief.'),
 q('士卒归田，皆颂{kingdom}之恩，耕战并兴。', '士卒歸田，皆頌{kingdom}之恩，耕戰並興。', 'The men take up the plough and praise the grace of {kingdom}; farming and arms both flourish.', 'Люди берутся за плуг, славя милость {kingdom}; земля и оружие процветают вместе.', '兵は田に帰り{kingdom}の恩を謳う——耕と戦が共に興る。', 'Die Männer greifen zum Pflug und preisen die Gnade von {kingdom}; Feld und Waffen gedeihen.'),
 q('赐金遣散', '賜金遣散', 'Give silver instead', 'Дать серебро', '金を賜う', 'Silber statt Land'),
 q('以金帛代田，量给之，功高者尚有差等。', '以金帛代田，量給之，功高者尚有差等。', 'Grant coin and silk in place of fields, in measured shares, with due difference for the most meritorious.', 'Выдать монету и шёлк вместо полей, в мерных долях, с должной разницей для самых заслуженных.', '田の代わりに金帛を量に応じて、功高き者には差をつけて与える。', 'Münze und Seide statt Felder, in bemessenen Gaben, mit angemessenem Unterschied für die Verdientesten.'),
 q('老兵得金而归，列国称{kingdom}念旧不吝。', '老兵得金而歸，列國稱{kingdom}念舊不吝。', 'Veterans go home with gold; realms praise {kingdom} for a generous memory of its old soldiers.', 'Ветераны уходят с золотом; соседи хвалят {kingdom} за щедрую память о старых солдатах.', '老兵は金を持ち帰り、諸国は{kingdom}の旧を思う気前の良さを称えた。', 'Veteranen ziehen heim mit Gold; Reiche rühmen die großzügige Erinnerung von {kingdom} an die alten Soldaten.')
)
ev('militia_rise', 2,
 ('民兵之兴', '民兵之興', 'The Militia Rises', 'Ополчение поднимается', '民兵の台頭', 'Die Landwehr erhebt sich'),
 ('乡勇屡败盗贼，声望日隆，竟自成一军。{king}当抚之或抑之。', '鄉勇屢敗盜賊，聲望日隆，竟自成一軍。{king}當撫之或抑之。', 'Village levies rout bandits again and again; their fame grows and they are all but an army. {king} may uphold or suppress them.', 'Сельские ополченцы вновь и вновь громят разбойников; слава растёт, и они почти армия. {king} может поддержать или подавить.', '郷の勇が盗賊を繰り返し破り、名声は日に高く、遂には一軍となった。{king}は撫でるか抑えるか。', 'Dorfmiliz schlägt Räuber immer wieder; ihr Ruf wächst, sie sind fast ein Heer. {king} kann stützen oder unterdrücken.'),
 q('抚而用之', '撫而用之', 'Uphold & use', 'Поддержать и использовать', '撫でて用いる', 'Stützen & nutzen'),
 q('授其首领名号，编入军籍，以佐王师。', '授其首領名號，編入軍籍，以佐王師。', 'Give their chief a title and enter them in the rolls to serve the royal host.', 'Дать их вождю звание и вписать в списки на службу царскому войску.', '首領に名号を授け軍籍に編入し、王師を助けさせる。', 'Dem Hauptmann einen Titel geben und sie in die Listen aufnehmen, dem Königsheer zu dienen.'),
 q('乡勇感奋，盗贼屏息，列国嘉{kingdom}之武。', '鄉勇感奮，盜賊屏息，列國嘉{kingdom}之武。', 'The levies are roused, bandits hold their breath, and realms commend the martial might of {kingdom}.', 'Ополченцы вдохновлены, разбойники затаились; соседи хвалят военную силу {kingdom}.', '郷勇は奮い立ち盗賊は息を潜め、諸国は{kingdom}の武を嘉した。', 'Die Miliz ist entfacht, die Räuber halten den Atem; Reiche loben die Wehrkraft von {kingdom}.'),
 q('勒令解散', '勒令解散', 'Order them home', 'Распустить', '解散を命ずる', 'Heimschicken'),
 q('夺其械散其众，乡勇衔恨，伏于阡陌。', '奪其械散其眾，鄉勇銜恨，伏於阡陌。', 'Take their arms and scatter their ranks; the levies nurse the grudge across the fields.', 'Отобрать оружие и распустить ряды; ополченцы носят обиду по полям.', '武器を奪い郷に散らせば、郷勇は恨みを胸に田畑に伏す。', 'Die Waffen nehmen, die Reihen zerstreuen; die Miliz trägt den Groll über die Felder.'),
 q('乡勇怨解甲之辱，暗聚山野，乱象隐伏。', '鄉勇怨解甲之辱，暗聚山野，亂象隱伏。', 'Smarting from the shame of disarmament, they gather in the hills by night — disorder lurks unseen.', 'Уязвлённые позором разоружения, они собираются в холмах — смута бродит невидимо.', '兵器を奪われた恥に怨み、夜ごと山野に集まる——乱の兆しが隠れて潜む。', 'Gekränkt von der Schmach der Entwaffnung sammeln sie sich nachts in den Hügeln — die Unruhe lauert unsichtbar.')
)
ev('spy_report', 2,
 ('敌营密报', '敵營密報', 'The Spy\'s Dispatch', 'Шпионское донесение', '敵陣の密書', 'Der Späherbericht'),
 ('细作冒死传回敌营布防之图，真价难辨。{king}当褒赏善加利用否。', '細作冒死傳回敵營佈防之圖，真價難辨。{king}當褒賞善加利用否。', 'A spy risks death to bring the enemy\'s defense map; its true worth is hard to tell. Should {king} reward and use it?', 'Лазутчик, рискуя жизнью, приносит карту обороны врага; трудно судить о цене. Должен ли {king} наградить и использовать?', '密偵が命を賭けて敵の布陣図を持ち帰る——真価は見極めにくい。{king}は褒賞して利用すべきか。', 'Ein Kundschafter bringt unter Lebensgefahr den Verteidigungsplan des Feindes; sein wahrer Wert ist schwer zu sagen. Soll {king} belohnen und nutzen?'),
 q('厚赏细作', '厚賞細作', 'Reward the spy', 'Наградить лазутчика', '密偵を厚く賞す', 'Den Kundschafter belohnen'),
 q('重金赏其功，命别将依图布阵。', '重金賞其功，命別將依圖布陣。', 'Reward the feat richly and bid a chosen general deploy by the map.', 'Богато наградить за подвиг и велеть избранному генералу строить по карте.', '重金を贈り、選ばれた将にその図に準じて陣を敷かせる。', 'Die Tat reich belohnen und einem auserwählten General befehlen, nach der Karte aufzustellen.'),
 q('谍人效死，敌情毕现，列国知{kingdom}善用间。', '諜人效死，敵情畢現，列國知{kingdom}善用間。', 'The spies give their lives; the enemy lies bare, and realms see that {kingdom} knows how to use its agents.', 'Шпионы отдают жизнь; враг зрим, и соседи видят, что {kingdom} умеет пользоваться своими лазутчиками.', '間者は命を捧げ、敵情は明らかに——諸国は{kingdom}の間者の使い方を知る。', 'Die Kundschafter geben ihr Leben; der Feind liegt blank, und Reiche sehen, dass {kingdom} seine Leute zu nutzen weiß.'),
 q('半信半疑', '半信半疑', 'Halve the trust', 'Верить вполовину', '半信半疑', 'Halbes Vertrauen'),
 q('薄赏其劳，图置案头，姑观其变。', '薄賞其勞，圖置案頭，姑觀其變。', 'Give a small reward, leave the map on the desk, and let events speak.', 'Дать малую награду, оставить карту на столе и смотреть, как развернутся дела.', '薄く慰労し、図を机に置いて成り行きを見る。', 'Eine kleine Gabe, die Karte auf den Tisch, die Dinge reden lassen.'),
 q('细作观望自保，密报渐稀，敌情蒙昧。', '細作觀望自保，密報漸稀，敵情蒙昧。', 'The spy lies low and guards himself; reports thin out and the enemy fades into fog.', 'Лазутчик затаился и бережёт себя; донесения редеют, враг тает в тумане.', '密偵は身を潜め、報せは疎らになり、敵情は霧に沈む。', 'Der Späher duckt sich und sichert sich selbst; die Meldungen dünnen, der Feind versinkt im Nebel.')
)
ev('ambush_warning', 2,
 ('伏兵之警', '伏兵之警', 'The Ambush Warning', 'Предупреждение о засаде', '伏兵の警告', 'Die Warnung vor dem Hinterhalt'),
 ('老斥候望见林间甲光，疑有伏兵于大道两侧，请{king}定夺行止。', '老斥候望見林間甲光，疑有伏兵於大道兩側，請{king}定奪行止。', 'An old scout sees glints of armor amid the woods and suspects an ambush along both flanks of the road. {king} must settle the march.', 'Старый лазутчик видит блеск доспехов в лесу и подозревает засаду на обоих флангах дороги. {king} должен решить марш.', '老斥候が林間に甲の光を見て、街道の両側に伏兵の疑いがあると告げる。{king}は行き先を定めねばならぬ。', 'Ein alter Kundschafter sieht Lichtschein von Harnischen im Holz und vermutet einen Hinterhalt an beiden Straßenflanken. {king} muss den Marsch festlegen.'),
 q('改道而行', '改道而行', 'Take the detour', 'Обойти', '道を変える', 'Umwege nehmen'),
 q('信其言，全军绕道，戒备而行。', '信其言，全軍繞道，戒備而行。', 'Trust his word; wheel the whole host off the road and march on guard.', 'Поверить слову; увести всё войско с дороги и идти настороже.', '言葉を信じ、全軍を迂回させ、警戒しながら進む。', 'Dem Wort trauen; das ganze Heer von der Straße schwenken, auf Wache marschieren.'),
 q('果遇伏于故道，全军无恙，列国称{kingdom}善听言。', '果遇伏於故道，全軍無恙，列國稱{kingdom}善聽言。', 'An ambush indeed waits on the old road; the host is unhurt, and realms praise {kingdom} for heeding counsel.', 'Засада действительно ждёт на старой дороге; войско невредимо, и соседи славят {kingdom} за верное ухо.', '果然旧道には伏兵が待っていた——全軍無事、諸国は{kingdom}の耳の良さを称えた。', 'Der Hinterhalt wartet wirklich auf dem alten Weg; das Heer ist unversehrt, und Reiche rühmen {kingdom} für gutes Hören.'),
 q('不信其言', '不信其言', 'Dismiss the word', 'Отмахнуться', '信じない', 'Die Rede verwerfen'),
 q('斥其疑神疑鬼，军行故道如常。', '斥其疑神疑鬼，軍行故道如常。', 'Mock his fears and march the old road as usual.', 'Высмеять его страхи и идти старой дорогой как обычно.', '疑心暗鬼と斥け、予定どおり旧道を行く。', 'Seine Ängste verspotten und wie gewohnt den alten Weg ziehen.'),
 q('幸而伏兵未动，虚惊一场，然险矣。', '幸而伏兵未動，虛驚一場，然險矣。', 'The ambush never stirs; a false alarm — and yet how near the danger came.', 'Засада не шевельнулась; ложная тревога — но как близка была беда.', '幸い伏兵は動かず、騒がずに済んだ——だが危うかった。', 'Der Hinterhalt regt sich nicht; ein falscher Alarm — und doch, wie nah kam die Not.')
)
ev('army_reduction', 2,
 ('裁军之议', '裁軍之議', 'The Army Cut', 'Сокращение армии', '軍の削減', 'Die Heeresreduktion'),
 ('四方无事，冗兵坐食。{king}议裁军以舒国用，安顿之法须先定。', '四方無事，冗兵坐食。{king}議裁軍以舒國用，安頓之法須先定。', 'All is quiet and idle troops eat the budget. {king} debates cutting the host to ease the chest — the resettlement must be fixed first.', 'Всё тихо, и праздные войска едят бюджет. {king} обсуждает сокращение войска ради казны — но устройство надо определить сперва.', '四方は静かで、余剰の兵が予算を食う。{king}は軍を削って国庫を楽にしようとする——が、離縁の手当てを先に定めねば。', 'Alles ist still, müßige Truppen fressen den Etat. {king} erwägt, das Heer zu kürzen, um die Kasse zu erleichtern — die Abfindung muss zuerst feststehen.'),
 q('善裁而安', '善裁而安', 'Cut with care', 'Сократить с заботой', '良く削って安んず', 'Mit Bedacht kürzen'),
 q('汰冗兵而给资归农，兵额减而库用舒。', '汰冗兵而給資歸農，兵額減而庫用舒。', 'Retire the surplus with passage-money to the plough; the ranks shrink and the chest breathes.', 'Отпустить лишних с подъёмными за плуг; ряды редеют, казна дышит.', '余剰の兵を除き旅費を与えて田に帰し、兵数を減らせば国庫は楽になる。', 'Die Überzähligen mit Reisegeld zum Pflug entlassen; die Ränge schrumpfen, die Kasse atmet.'),
 q('冗兵既裁，库帑渐盈，军械之费亦有所蓄。', '冗兵既裁，庫帑漸盈，軍械之費亦有所蓄。', 'With the surplus gone the treasury slowly fills, and funds for arms are gathered again.', 'С лишними уйдя, казна понемногу полнится; средства на оружие копятся вновь.', '余剰を除けば国庫は次第に満ち、武器の費用も貯えられる。', 'Mit den Überzähligen füllt sich die Kasse langsam; Mittel für Waffen sammeln sich wieder an.'),
 q('急裁不恤', '急裁不恤', 'Cut without comfort', 'Сократить без утешения', '無配慮の即断', 'Kürzen ohne Trost'),
 q('径裁额数而无资遣，罢卒聚于道，怨声沸。', '徑裁額數而無資遣，罷卒聚於道，怨聲沸。', 'Strike the numbers at once with no settlement; the cast-off soldiers crowd the roads, boiling with resentment.', 'Вычеркнуть разом без устройства; отставленные толпятся на дорогах, кипя обидой.', '数だけ一括で削り手当てもなく、解かれた兵が道に集まり、怨みの声が沸く。', 'Die Zahlen auf einen Streich streichen ohne Abfindung; die Entlassenen drängen die Wege, vor Groll sieden.'),
 q('罢卒群聚都门，斥责之声四起，乱象将萌。', '罷卒群聚都門，斥責之聲四起，亂象將萌。', 'The cast-offs mass at the capital gates, curses rising on every side; disorder is about to sprout.', 'Отставленные толпятся у ворот столицы, проклятия со всех сторон; смута вот-вот даст побеги.', '罷免の群れが都門に集まり、罵声が四方に轟く——乱の兆しが芽生えようとしている。', 'Die Entlassenen stauen sich an den Toren der Hauptstadt, Flüche von allen Seiten; Unordnung will keimen.')
)
ev('war_trophy', 2,
 ('战利归库', '戰利歸庫', 'The War Spoils', 'Военные трофеи', '戦利品の収公', 'Die Kriegsbeute'),
 ('大军破城，所得金银降表如山。{king}命归库抽分，以实国用。', '大軍破城，所得金銀降表如山。{king}命歸庫抽分，以實國用。', 'The host takes a city; gold, silver, and the surrender roll pile like mountains. {king} orders the spoils reckoned into the treasury.', 'Войско берёт город; золото, серебро и счёт покорных горой. {king} велит свести добычу в казну.', '大軍が城を破り、金銀と降服の文書が山となる。{king}は戦利品を国庫に収めるよう命じる。', 'Das Heer nimmt eine Stadt; Gold, Silber und die Übergabeliste türmen sich wie Berge. {king} heißt die Beute in die Kasse rechnen.'),
 q('尽陈王庭', '盡陳王庭', 'Present at court', 'Свести ко двору', 'すべて王庭へ', 'Am Hofe vorlegen'),
 q('辎重数万尽入王库，赏功者以次予之。', '輜重數萬盡入王庫，賞功者以次予之。', 'Bring wagon-loads of spoils into the treasury and reward the meritorious in turn.', 'Обозы добычи в хранилище; наградить достойных по очереди.', '奪った荷をすべて王庫に運び、功ある者へ順に褒賞する。', 'Wagenladungen der Beute ins Gewölbe bringen und die Verdienten der Reihe nach belohnen.'),
 q('金库为之一丰，{kingdom}挥师之气更盛；列国亦嘉而惧之。', '金庫為之一豐，{kingdom}揮師之氣更盛；列國亦嘉而懼之。', 'The treasury swells; {kingdom} marches with a prouder air, and realms both praise and fear it.', 'Казна пухнет; {kingdom} идёт с гордым видом, и соседи и хвалят, и боятся.', '国庫は豊かになり、{kingdom}の軍勢はいっそう威風——諸国は讃えかつ恐れた。', 'Die Kasse schwillt; {kingdom} zieht stolzer einher, Reiche loben und fürchten.'),
 q('分赏诸将', '分賞諸將', 'Share with the chiefs', 'Поделить с вождями', '諸将に分け与える', 'Mit den Führern teilen'),
 q('与诸将分功，各有所得，群雄色动。', '與諸將分功，各有所得，群雄色動。', 'Divide the merit with the generals; each takes his due and their faces kindle.', 'Разделить заслугу с генералами; каждый берёт своё, и лица загораются.', '功を将たちと分けて、それぞれが受け取り、群雄の目が輝く。', 'Das Verdienst mit den Generälen teilen; jeder nimmt sein Teil und die Gesichter feuern.'),
 q('将士感奋，{kingdom}之名扬于列国，军势愈张。', '將士感奮，{kingdom}之名揚於列國，軍勢愈張。', 'The officers and men are roused; the name of {kingdom} flies abroad and the host grows bolder.', 'Офицеры и солдаты воодушевлены; имя {kingdom} летит за рубеж, войско становится смелее.', '将兵は感奮し、{kingdom}の名は諸国に轟き、軍勢はますます勢いづく。', 'Offiziere und Mannschaften sind entfacht; der Name von {kingdom} fliegt hinaus, das Heer wird kühner.')
)
ev('general_madness', 2,
 ('将狂之变', '將狂之變', 'The Mad General', 'Безумный генерал', '将の狂乱', 'Der wahnsinnige General'),
 ('名将忽发狂疾，于帐中挥剑斩吏。诸军惊骇，{king}当如何处之。', '名將忽發狂疾，於帳中揮劍斬吏。諸軍驚駭，{king}當如何處之。', 'A famed captain suddenly runs mad and cuts down clerks with his sword in the tent. The host is aghast; {king} must deal with it.', 'Прославленный вождь внезапно обезумел и изрубил писцов мечом в шатре. Войско в ужасе; {king} должен решить.', '名将が突然狂い、幕中で剣を振るい吏を斬り倒した。諸軍は震え上がり、{king}は処断を迫られる。', 'Ein berühmter Feldherr wird plötzlich rasend und schlägt mit dem Schwert Schreiber im Zelt nieder. Das Heer erstarrt; {king} muss damit umgehen.'),
 q('夺职系狱', '奪職繫獄', 'Strip & jail him', 'Снять и заточить', '職を奪い繋ぐ', 'Abnehmen & festsetzen'),
 q('收其印剑械系之，三军震恐而亦疑。', '收其印劍械繫之，三軍震恐而亦疑。', 'Take his seal and sword and fetter him; the host is shaken and begins to doubt.', 'Взять печать и меч и сковать его; войско потрясено и начинает сомневаться.', '印と剣を奪い縛すれば、三軍は震え恐怖と疑いを抱く。', 'Siegel und Schwert nehmen, ihn fesseln; das Heer erzittert und beginnt zu zweifeln.'),
 q('狂将系狱，军法得申；然旧部怅怅，军中龃龉暗生。', '狂將繫獄，軍法得申；然舊部悵悵，軍中齟齬暗生。', 'The madman sits in gaol and military law is upheld; yet his old comrades grieve and friction builds unseen.', 'Безумец в темнице, военный закон соблюдён; но старые товарищи скорбят, и трение растёт незримо.', '狂将は獄にあり軍法は守られた——だが旧部下は悲しみ、軍に暗い亀裂が生まれる。', 'Der Rasende sitzt im Kerker, das Kriegsrecht ist gewahrt; doch die alten Kameraden trauern, Reibung wächst unsichtbar.'),
 q('宽宥养病', '寬宥養病', 'Pardon and rest', 'Простить и лечить', '許して養わせる', 'Vergeben & heilen'),
 q('释其罪，命归府养病，朝野侧目。', '釋其罪，命歸府養病，朝野側目。', 'Absolve him and bid him heal at his mansion; court and camp look askance.', 'Оправдать и велеть лечиться в усадьбе; двор и лагерь косятся.', '罪を赦し邸に帰して養わせれば、朝野の目が刺す。', 'Freisprechen, in seinem Haus heilen heißen; Hof und Lager blicken scheel.'),
 q('狂将得全，法纪稍弛；将士窃议，疑云不散。', '狂將得全，法紀稍弛；將士竊議，疑雲不散。', 'The madman lives and discipline slackens; officers whisper and the clouds of doubt will not lift.', 'Безумец жив, дисциплина увядает; офицеры шепчутся, и тучи сомнения не тают.', '狂将は命を保ち規律はやや緩む——将兵は囁き、疑いの雲は去らぬ。', 'Der Rasende lebt, die Zucht erschlafft; Offiziere flüstern, und die Wolken des Zweifels weichen nicht.')
)
ev('barracks_brawl', 2,
 ('营中斗殴', '營中鬥毆', 'The Barracks Brawl', 'Драка в казармах', '兵営の喧嘩', 'Die Rauferei in der Kaserne'),
 ('两营士卒因酒角功，斗于营门，伤者百余人。{king}须平其隙。', '兩營士卒因酒角功，鬥於營門，傷者百餘人。{king}須平其隙。', 'Men of two battalions fall to blows over wine and honor at the camp gate; more than a hundred are hurt. {king} must close the rift.', 'Солдаты двух батальонов сходятся в драке за вино и честь у лагерных ворот; ранено больше сотни. {king} должен закрыть трещину.', '二つの隊の兵が酒と功を巡り陣門で乱闘し、百人余りが傷ついた。{king}は溝を埋めねばならぬ。', 'Männer zweier Bataillone geraten um Wein und Ehre am Lagertor aneinander; über hundert sind verletzt. {king} muss den Riss schließen.'),
 q('重惩首事', '重懲首事', 'Punish the ringleaders', 'Наказать зачинщиков', '首謀を重く罰す', 'Die Rädelsführer strafen'),
 q('枷首事者于辕门，惩其魁而安其众。', '枷首事者於轅門，懲其魁而安其眾。', 'Put the ringleaders in the cangue at the camp gate; punish the heads and calm the rest.', 'Забить зачинщиков в колодки у лагерных ворот; наказать главарей, успокоить остальных.', '首謀者を陣門の木枷につなぎ、魁を罰して残りを静める。', 'Die Anführer in den Pranger am Lagertor legen; die Häupter strafen, die Menge stillen.'),
 q('斗殴暂息，然两营积怨未解，私斗时发。', '鬥毆暫息，然兩營積怨未解，私鬥時發。', 'The brawl sleeps, yet the old grudges of the two battalions remain and private fights break out.', 'Драка спит, но старая вражда остаётся, и частные стычки вспыхивают.', '乱闘は収まるが、両隊の恨みは残り、私闘があちこちで起きる。', 'Die Rauferei schläft, doch der alte Groll der Bataillone bleibt, und Privatfehden brechen aus.'),
 q('调和置酒', '調和置酒', 'Reconcile with wine', 'Помирить вином', '酒を酌んで和す', 'Mit Wein versöhnen'),
 q('召两营管带共饮，令其释怨结好。', '召兩營管帶共飲，令其釋怨結好。', 'Call both commanders to drink together and make them lay down the quarrel.', 'Позвать обоих командиров на вино и заставить отбросить ссору.', '両隊の長を招いて杯を交わさせ、怨みを捨てて結ばせる。', 'Beide Kommandeure zum Trunk rufen, den Zwist ablegen lassen.'),
 q('酒罢揖让，怨气稍解，然未几又起口舌。', '酒罷揖讓，怨氣稍解，然未幾又起口舌。', 'After the wine they bow to each other and the anger softens — yet tongues soon clash again.', 'После вина они раскланиваются, гнев смягчён — но языки вскоре снова скрещиваются.', '酒がすめば揖譲し、怒りは少し解ける——だが舌戦はすぐに再燃する。', 'Nach dem Wein verneigen sie sich, der Zorn weicht — doch die Zungen stoßen bald erneut.')
)
ev('supply_shortfall', 2,
 ('粮道不继', '糧道不繼', 'The Supply Gap', 'Разрыв снабжения', '兵糧の途絶', 'Der Nachschubriss'),
 ('大军围城已月，粮道为敌所断，仓廪日罄。{king}须谋补给之策。', '大軍圍城已月，糧道為敵所斷，倉廩日罄。{king}須謀補給之策。', 'The host has besieged the city a month; the enemy severs the grain road and the stores empty day by day. {king} must plan resupply.', 'Войско осаждает город месяц; враг режет зерновую дорогу, склады пустеют день ото дня. {king} должен спланировать снабжение.', '大軍は城を一月囲むが、敵に糧道を断たれ倉は日に日に空く。{king}は補給の策を練らねばならぬ。', 'Das Heer belagert die Stadt seit einem Monat; der Feind schneidet die Kornstraße, die Speicher leeren sich Tag für Tag. {king} muss den Nachschub planen.'),
 q('重金购粮', '重金購糧', 'Buy grain dear', 'Купить хлеб дорого', '重金で買う', 'Korn teuer kaufen'),
 q('发内帑多方购粮输军，价腾而役苦。', '發內帑多方購糧輸軍，價騰而役苦。', 'Draw from the inner treasury to buy grain from every quarter and haul it to the host; prices soar, the toil bites.', 'Опорожнить внутреннюю казну на хлеб отовсюду; цены взлетают, труд кусает.', '内庫を割いて四方から穀物を買い軍に送れば、価格は跳ね上がり人足も辛い。', 'Aus der inneren Kasse Korn von allen Seiten kaufen und heranschaffen; die Preise steigen, die Mühsal beißt.'),
 q('粮秣复续，军心稍安；库帑则渐见底。', '糧秣復續，軍心稍安；庫帑則漸見底。', 'Provisions flow again and hearts ease a little, while the treasury begins to show its bottom.', 'Припасы идут вновь, сердца чуть легче; казна начинает показывать дно.', '糧は継ぎ軍心は少し安んじる——国庫は底を見せ始める。', 'Proviant fließt wieder, die Herzen leichten sich; die Kasse zeigt allmählich ihren Grund.'),
 q('就地征粮', '就地徵糧', 'Forage the fields', 'Собирать с полей', '野で徴発する', 'Die Felder absuchen'),
 q('命军四出括粮于野，民舍为之一空。', '命軍四出括糧於野，民舍為之一空。', 'Send the host sweeping the countryside for grain; the homesteads stand empty.', 'Послать войско прочёсывать округу ради зерна; дома стоят пустыми.', '軍を野に送り村々から穀物をかき集めさせれば、民家は空になる。', 'Das Heer die Landschaft auskämmen lassen, Korn zu raffen; die Höfe stehen leer.'),
 q('民怨四起，乱象萌动，军中亦有哗断之虞。', '民怨四起，亂象萌動，軍中亦有譁斷之虞。', 'Village fury rises on all sides, disorder stirs, and even in the host there is fear of a mutinous break.', 'Гнев деревень растёт, смута шевелится, и даже в войске боятся мятежного разрыва.', '民の怨みが四方に上がり乱の兆しが蠢き、軍中にも反乱の断絶の恐れがある。', 'Dorffuror steigt von allen Seiten, die Unruhe regt sich, und selbst im Heer ist Furcht vor dem meuternden Bruch.')
)
ev('battlefield_courage', 2,
 ('阵前夺旗', '陣前奪旗', 'Courage Before the Lines', 'Храбрость в строю', '陣前の勇', 'Mut vor der Schlachtreihe'),
 ('两军鏖战之际，一卒奋戟夺敌军旗，三军士气得为之一振。', '兩軍鏖戰之際，一卒奮戟奪敵軍旗，三軍士氣得為之一振。', 'Amid the grinding battle a single soldier seizes the enemy banner with his halberd; the host\'s spirits leap as one.', 'В изнурительной битве один солдат вырывает вражеское знамя алебардой; дух войска взлетает как один.', '両軍が鍔迫り合う中、一兵が戟を振るい敵の軍旗を奪い取った——三軍の士気が一斉に跳ね上がる。', 'Im schleifenden Gefecht entreißt ein Soldat mit der Hellebarde das feindliche Banner; der Geist des Heeres springt wie einer auf.'),
 q('表旌三军', '表旌三軍', 'Proclaim to all', 'Огласить повсюду', '三軍に示す', 'Allen verkünden'),
 q('传檄三军表其勇，逐级嘉赏弗替。', '傳檄三軍表其勇，逐級嘉賞弗替。', 'Spread the deed through the host and grant rewards at every rank without stint.', 'Разослать подвиг по войску и дать награды на каждой ступени без скупости.', '全軍に檄を飛ばしその勇を顕し、階級ごとに惜しみなく褒賞する。', 'Die Tat durchs Heer tragen und auf jeder Stufe ohne Knauserei belohnen.'),
 q('勇士之名传遍营伍，列国争传{kingdom}将士之勇。', '勇士之名傳遍營伍，列國爭傳{kingdom}將士之勇。', 'The hero\'s name flies through every camp; realms vie to retell the valor of {kingdom}\'s soldiers.', 'Имя героя летит по всем лагерям; соседи наперебой пересказывают доблесть солдат {kingdom}.', '勇士の名は全陣に響き、諸国は{kingdom}の兵の武勇を争って伝えた。', 'Der Heldname fliegt durch jedes Lager; Reiche wetteifern, die Tapferkeit der Soldaten von {kingdom} zu erzählen.'),
 q('叙功搁置', '敘功擱置', 'Lay the merit by', 'Отложить заслугу', '功績を閤に置く', 'Das Verdienst vertagen'),
 q('功薄而赏迟，勇者怅然，麾下亦赧然。', '功薄而賞遲，勇者悵然，麾下亦赧然。', 'The record is thin and the reward late; the brave man grieves and his men blush with him.', 'Запись скудна и награда поздняя; храбрец скорбит, его люди краснеют вместе с ним.', '功の記録は薄く褒賞は遅く、勇者は憂い、部下も顔を赤らめる。', 'Der Eintrag ist dünn und die Gabe spät; der Tapfere trauert, seine Leute erröten mit ihm.'),
 q('其功未能孚众，士气受挫，惟军纪尚无大碍。', '其功未能孚眾，士氣受挫，惟軍紀尚無大礙。', 'His merit wins no heed and morale sags, though the order of the host suffers no great harm.', 'Его заслуга не встречает признания, дух падает, хотя порядку войска нет большого вреда.', 'その功は衆に認められず士気は挫かれた——幸い軍紀には大した害がない。', 'Sein Verdienst findet kein Gehör, der Geist sinkt, doch die Ordnung des Heeres leidet keinen großen Schaden.')
)
ev('victory_parade', 2,
 ('凯旋之典', '凱旋之典', 'The Triumph Parade', 'Триумфальный парад', '凱旋の式典', 'Der Triumphzug'),
 ('大军奏凯还朝，{king}欲举行献俘之礼，大飨三军，费帑可观。', '大軍奏凱還朝，{king}欲舉行獻俘之禮，大饗三軍，費帑可觀。', 'The host returns in triumph to the court; {king} would hold a rite of presented captives and feast all three armies — a handsome outlay.', 'Войско возвращается с триумфом ко двору; {king} хочет провести обряд пленных и пир всего войска — расход щедр.', '大軍が勝ち鬨を上げて朝に還る。{king}は献俘の礼を行い三軍を大いに饗すか——費用は見事なものだ。', 'Das Heer kehrt im Triumpf zum Hof zurück; {king} will den Ritus der vorgeführten Gefangenen halten und alle drei Heere bewirten — ein stattlicher Aufwand.'),
 q('盛典犒师', '盛典犒師', 'Grand feast & rite', 'Великий пир и обряд', '盛大に饗す', 'Großer Schmaus & Ritus'),
 q('出帑犒三军，封赏战功，献俘太庙。', '出帑犒三軍，封賞戰功，獻俘太廟。', 'Spend from the chest to feast the host, enfeoff the battle merits, and present the captives at the shrine.', 'Потратить из казны: пир войску, пожаловать заслуги, привести пленных в святилище.', '庫から出して三軍を饗し、戦功を賞し、捕虜を太廟に献じる。', 'Aus der Kasse das Heer bewirten, die Kriegsverdienste belehnen, die Gefangenen am Heiligtum vorführen.'),
 q('礼成之日，列国使节齐贺{kingdom}武功，金帛亦如流水。', '禮成之日，列國使節齊賀{kingdom}武功，金帛亦如流水。', 'On the day the rites close, envoys from every realm congratulate the martial might of {kingdom}; gold and silk flow like water.', 'В день свершения обряда послы всех держав поздравляют военную силу {kingdom}; золото и шёлк текут как вода.', '礼の日、列国の使節が揃って{kingdom}の武功を祝い、金帛は水のように流れた。', 'Am Tage der Riten gratulieren Gesandte aller Reiche der Wehrkraft von {kingdom}; Gold und Seide fließen wie Wasser.'),
 q('只犒不言', '只犒不言', 'Meat, no rite', 'Мясо без обряда', '酒肉のみ', 'Fleisch ohne Ritus'),
 q('给酒肉犒之，不行大礼，免其繁费。', '給酒肉犒之，不行大禮，免其繁費。', 'Give them meat and wine only, without the great rite, sparing the heavy cost.', 'Дать лишь мясо и вино, без великого обряда, сберегая тяжкий расход.', '酒と肉を振る舞うだけで大礼は行わず、重い費用を省く。', 'Nur Fleisch und Wein geben, ohne den großen Ritus, die schwere Ausgabe sparen.'),
 q('士卒饱餐而队队归营，无盛名亦无乱象。', '士卒飽餐而隊隊歸營，無盛名亦無亂象。', 'The soldiers feast well and troop back by company — no resounding fame, and no disorder either.', 'Солдаты довольны пиром и уходят ротами — ни громкой славы, ни смуты.', '兵は満腹して隊を組んで帰営——華々しい名声もなく乱れもない。', 'Die Soldaten speisen gut und ziehen truppweise ins Lager — kein dröhnender Ruhm, keine Unruhe.')
)
ev('troop_resupply', 2,
 ('前线粮械', '前線糧械', 'The Forward Resupply', 'Пополнение на фронте', '前線の補給', 'Der Frontnachschub'),
 ('前线器械折损过半，弓矢不继。{king}当速发帑运补，或听其自便。', '前線器械折損過半，弓矢不繼。{king}當速發帑運補，或聽其自便。', 'At the front more than half the gear is broken and arrows run out. {king} may send supplies in haste, or let them shift for themselves.', 'На фронте больше половины снаряжения переломано, стрелы на исходе. {king} может срочно слать припасы или оставить самим.', '前線では武具が半数壊れ、矢が尽きかけている。{king}は急いで物資を送るか、自ら調達させよと言うか。', 'An der Front ist über die Hälfte des Geräts zerbrochen, die Pfeile gehen aus. {king} kann eilends Nachschub senden oder sie sich selbst helfen lassen.'),
 q('发帑运补', '發帑運補', 'Ship them supplies', 'Слать припасы', '物資を送る', 'Nachschub senden'),
 q('采办弓矢甲仗，星夜解送前线。', '採辦弓矢甲仗，星夜解送前線。', 'Buy bows, arrows, and armor, and race them to the front by night and day.', 'Купить луки, стрелы и броню и мчать на фронт днём и ночью.', '弓矢と甲冑を買い求め、昼夜で前線へ運ばせる。', 'Bögen, Pfeile und Panzer kaufen und Tag und Nacht an die Front jagen.'),
 q('器械得补，军势复振；所费之帑亦颇可观。', '器械得補，軍勢復振；所費之帑亦頗可觀。', 'Gear is made whole and the host revives; the outlay is considerable.', 'Снаряжение цело, войско оживает; расход значителен.', '武具は再び整い軍勢は息を吹き返す——費用もまた見事な額だ。', 'Das Gerät ist heil, das Heer lebt auf; der Aufwand ist beträchtlich.'),
 q('责令自筹', '責令自籌', 'Provide for yourselves', 'Доставать самим', '自前でやれ', 'Selbst beschaffen'),
 q('谕前线于敌境自取，取之民间则民怨起。', '諭前線於敵境自取，取之民間則民怨起。', 'Bid the front seize what it needs from enemy lands — but taking from the people stirs their wrath.', 'Велеть фронту взять нужное в землях врага — но брать у народа будит гнев.', '敵地で自ら調達せよと言えば、民から奪えば民の怨みが起きる。', 'Die Front heißen, aus Feindesland zu nehmen — vom Volk nehmen weckt dessen Zorn.'),
 q('士卒剽掠乡野，怨声载道，军纪亦堕。', '士卒剽掠鄉野，怨聲載道，軍紀亦墮。', 'The soldiers plunder the countryside; the outcry fills the roads and discipline falls.', 'Солдаты грабят округу; вопль полнит дороги, дисциплина падает.', '兵は郷野を掠め、怨嗟が道に溢れ、軍紀も堕ちた。', 'Die Soldaten plündern das Land; das Geschrei füllt die Wege, die Zucht fällt.')
)
ev('general_protector', 2,
 ('倚重老将', '倚重老將', 'The Old Protector', 'Старый защитник', '老将の重鎮', 'Der alte Schirmherr'),
 ('老将素有宿望，上疏请总戎政、肃军容。{king}当委以大任或存其疑。', '老將素有宿望，上疏請總戎政、肅軍容。{king}當委以大任或存其疑。', 'An old general of long-standing renown petitions to take command of the whole war policy and tighten the host. {king} may trust him fully or hold him in doubt.', 'Старый генерал давней славы просит взять всю военную политику и подтянуть войско. {king} может вверить ему всё или сомневаться.', '宿望ある老将が手を上げて軍政を総覧し軍容を引き締めよと請う。{king}は大任を委ねるか、疑いを抱くか。', 'Ein alter General von altem Ruf bittet, die ganze Kriegspolitik zu übernehmen und das Heer zu straffen. {king} mag ihm alles anvertrauen oder ihn im Zweifel halten.'),
 q('委以大任', '委以大任', 'Entrust him all', 'Вверить всё', '大任を委ねる', 'Ihm alles anvertrauen'),
 q('拜为大都护，总揽戎政，三军肃然。', '拜為大都護，總攬戎政，三軍肅然。', 'Name him protector of all arms, holding the whole war government; the host falls into reverence.', 'Назвать его защитником всех родов с полной военной властью; войско в благоговении.', '大都護に任じ軍政を総覧させれば、三軍は粛然と整う。', 'Zum Beschützer aller Waffen ernennen mit ganzer Kriegsgewalt; das Heer fällt in Ehrfurcht.'),
 q('军令严明，甲胄齐备，列国争相与{kingdom}交。', '軍令嚴明，甲胄齊備，列國爭相與{kingdom}交。', 'Orders run strict and armor stands ready; realms now vie to renew their friendship with {kingdom}.', 'Приказы строги, броня готова; державы теперь наперебой обновляют дружбу с {kingdom}.', '軍令は厳正、武具は揃い、諸国は争って{kingdom}と交誼を結ぼうとする。', 'Befehle laufen streng, Panzer stehen bereit; Reiche wetteifern, die Freundschaft mit {kingdom} zu erneuern.'),
 q('收其兵柄', '收其兵柄', 'Take his sword', 'Отнять меч', '兵権を収める', 'Sein Schwert nehmen'),
 q('惧其功高，收其兵柄，老将拂衣而去。', '懼其功高，收其兵柄，老將拂衣而去。', 'Fearing his glory, take away his command; the old general sweeps off his sleeves and leaves.', 'Убоявшись славы, снять с него командование; старый генерал уходит, метнув рукав.', '功の高さを恐れて兵権を奪えば、老将は袖を払って去る。', 'Den Ruhm fürchten, ihm das Kommando abnehmen; der alte General wirft die Ärmel und zieht davon.'),
 q('老将恚恨去国，部曲哗然，军中颇有离心。', '老將恚恨去國，部曲譁然，軍中頗有離心。', 'The old general leaves the realm in wrath; his followers are in an uproar and disaffection creeps through the host.', 'Старый генерал уходит из державы в гневе; его люди в смятении, в войске крадётся рознь.', '老将は憤って国を去り、配下は騒然とし、軍中に離心の気配が忍び寄る。', 'Der alte General verlässt das Reich im Zorn; seine Leute lärmen, im Heer kriecht die Entfremdung.')
)
ev('border_feast', 2,
 ('犒边之宴', '犒邊之宴', 'The Border Feast', 'Пир на границе', '辺境の宴', 'Das Grenzfest'),
 ('岁末戍卒劳苦，边将请开宴犒军，兼邀邻邦观礼。{king}当允与否。', '歲末戍卒勞苦，邊將請開宴犒軍，兼邀鄰邦觀禮。{king}當允與否。', 'At year\'s end the border troops are weary; the warden begs leave to feast them and invite the neighbor envoys to witness. Should {king} allow it?', 'В конце года пограничники устали; воевода просит пира для них и приглашения соседних послов. Позволит ли {king}?', '年の瀬、辺境の兵は疲れている。辺将が兵を労う宴を開き、隣国を観礼に招こうと請う。{king}は許すか。', 'Zum Jahresende sind die Grenzsoldaten müde; der Grenzmeister bittet um ein Festmahl für sie und die Nachbargesandten als Zuschauer. Erlaubt {king} es?'),
 q('开宴犒军', '開宴犒軍', 'Open the feast', 'Открыть пир', '宴を開く', 'Das Fest öffnen'),
 q('发帑设宴，厚犒戍卒，并邀邻使。', '發帑設宴，厚犒戍卒，並邀鄰使。', 'Spend from the chest: a rich feast for the garrison, with the neighbor envoys invited.', 'Потратить из казны: богатый пир гарнизону, приглашены и соседние послы.', '庫から出して宴を設け、戍卒を厚く労い、隣国の使節も招く。', 'Aus der Kasse ein Mahl geben, die Besatzung reichlich bewirten, die Nachbargesandten laden.'),
 q('士卒拊掌皆欢，邻邦使者亦衔欢，{kingdom}边烽晏然。', '士卒拊掌皆歡，鄰邦使者亦銜歡，{kingdom}邊烽晏然。', 'The soldiers clap in joy and the envoys smile with them; the border beacons of {kingdom} rest quiet.', 'Солдаты рукоплещут от радости, послы улыбаются им; пограничные маяки {kingdom} покойны.', '兵は手を叩いて喜び、隣国の使節も笑み——{kingdom}の辺境の烽火は穏やかだ。', 'Die Soldaten klatschen vor Freude, die Gesandten lächeln mit; die Grenzzeichen von {kingdom} ruhen still.'),
 q('罢宴省费', '罷宴省費', 'Call it off', 'Отменить', '宴を取りやめる', 'Absagen'),
 q('谢边将之请，罢宴而止，戍卒循例。', '謝邊將之請，罷宴而止，戍卒循例。', 'Thank the warden and decline the feast; the garrison keeps the old routine.', 'Поблагодарить воеводу и отказаться от пира; гарнизон держится старого порядка.', '辺将の請いを謝して宴を取りやめ、戍卒は例の通りに。', 'Dem Grenzmeister danken und das Mahl absagen; die Besatzung folgt dem alten Brauch.'),
 q('库帑有省，士卒无怨，惟边谊稍疏。', '庫帑有省，士卒無怨，惟邊誼稍疏。', 'The chest saves and the men bear no grudge; only the neighborly bond has cooled a little.', 'Казна сберегла, люди не в обиде; лишь соседская связь остыла чуть-чуть.', '国庫は省け兵も不満はない——ただ隣国との誼が少し疎くなった。', 'Die Kasse spart, die Männer tragen nichts nach; nur das nachbarliche Band ist ein wenig erkaltet.')
)
ev('archery_club', 2,
 ('射艺之社', '射藝之社', 'The Archery Club', 'Лучный клуб', '弓術の会', 'Der Schützenverein'),
 ('贵族子弟竞尚射艺，设社于郊外。{king}欲亲自赐额名以宠之。', '貴族子弟競尚射藝，設社於郊外。{king}欲親自賜額名以寵之。', 'Nobles\' sons vie in archery and found a club outside the walls. {king} would grace it with a plaque and name of his own hand.', 'Дворянские сыновья состязаются в стрельбе и основали клуб за стенами. {king} хочет подарить ему вывеску и имя от своей руки.', '貴族の子弟たちが弓術を競い、郊外に会を設けた。{king}は自ら額の名を賜って寵愛したい。', 'Adelssöhne wetteifern im Bogenschießen und gründen einen Verein vor den Mauern. {king} will ihn mit einer Tafel und eigenem Namen ehren.'),
 q('赐额之宠', '賜額之寵', 'Grant the title', 'Дать титул', '額を賜う', 'Den Namen schenken'),
 q('亲题社名，赐弓矢诸器以奖之。', '親題社名，賜弓矢諸器以獎之。', 'Inscribe the name yourself and bestow bows and gear to reward them.', 'Надписать имя сам и пожаловать луки и снаряжение в награду.', '自ら名を書き、弓矢の品々を賜って励ます。', 'Den Namen selbst schreiben und Bogen und Gerät zur Gabe stiften.'),
 q('子弟感奋，射艺大行，列国称{kingdom}彬彬能武。', '子弟感奮，射藝大行，列國稱{kingdom}彬彬能武。', 'The youths are stirred and archery flourishes; realms call {kingdom} courteous and martial at once.', 'Юнцы воодушевлены, стрельба процветает; соседи зовут {kingdom} и учтивым, и воинственным.', '子弟は奮い立ち弓術が大いに盛んに——諸国は{kingdom}を文武兼ね備えと称えた。', 'Die Jungen sind entfacht, die Kunst blüht; Reiche nennen {kingdom} höflich und wehrhaft zugleich.'),
 q('听其自会', '聽其自會', 'Let them be', 'Пусть будут', '自主に任せる', 'Sie lassen'),
 q('不赐名号，任其自会出没。', '不賜名號，任其自會出沒。', 'Give no title; let the club keep to its own gatherings.', 'Не давать имени; пусть клуб держится своих сходок.', '名号は賜わず、会の集まりに任せる。', 'Keinen Namen geben; der Verein hält seine eigenen Treffen.'),
 q('社中如常习射，无恩宠亦无风波。', '社中如常習射，無恩寵亦無風波。', 'The club shoots on as always — no royal favor, no turbulence.', 'Клуб стреляет как всегда — ни милости, ни смуты.', '会はいつものように稽古する——恩寵も波風もない。', 'Der Verein schießt wie immer — keine fürstliche Gunst, keine Unruhe.')
)
ev('watchtower_signal', 2,
 ('烽燧之修', '烽燧之修', 'The Beacon Towers', 'Маячные башни', '烽火の修繕', 'Die Signalzeichen'),
 ('沿边烽燧年久失修，烽火每多不能达。{king}欲出资重修诸台。', '沿邊烽燧年久失修，烽火每多不能達。{king}欲出資重修諸台。', 'The border beacon towers have long stood unkept and the fire-signals often fail to reach. {king} would spend to restore them all.', 'Пограничные маячные башни давно стоят не ухожены, и огненные сигналы часто не долетают. {king} хочет потратиться на восстановление всех.', '国境の烽火台は長く手入れされず、火の信号がしばしば届かない。{king}は諸台の再建に金を出したい。', 'Die Grenzsignaltürme stehen lange ungepflegt, und die Feuersignale kommen oft nicht durch. {king} will Geld für die Wiederherstellung aller geben.'),
 q('出资重修', '出資重修', 'Fund the repair', 'Оплатить ремонт', '金を出して修す', 'Reparatur bezahlen'),
 q('发帑补葺诸台，招揆吏守之。', '發帑補葺諸台，招揆吏守之。', 'Spend on mending every tower and hire careful keepers to watch them.', 'Потратиться на починку всех башен и нанять рачительных смотрителей.', '金を出して諸台を修め、見張りの吏を雇う。', 'Geld für die Reparatur aller Türme und den Dienst sorgsamer Wächter ausgeben.'),
 q('烽燧相望，警报立通；金帛亦随役而耗。', '烽燧相望，警報立通；金帛亦隨役而耗。', 'Beacons watch each other across the line and alarms carry at once; gold and silk drain with the works.', 'Маяки перекликаются через линию, тревоги долетают вмиг; золото и шёлк уходят с работами.', '烽火が互いを望み警報は即座に届く——金と帛も工事と共に減る。', 'Die Zeichen sehen einander, Alarme tragen sogleich; Gold und Seide rinnen mit den Werken davon.'),
 q('因陋就简', '因陋就簡', 'Patch the worst', 'Латать худшее', '急所を繕う', 'Das Schlimmste flicken'),
 q('仅命巡检修补一二，余台仍旧。', '僅命巡檢修補一二，餘台仍舊。', 'Only bid the patrol to mend two or three in passing; the rest stand as before.', 'Поручить дозору починить лишь две-три мимоходом; прочие стоят как прежде.', '巡視に壊れた一二台だけ直させ、残りはそのまま置く。', 'Der Patrouille heißen, nur zwei oder drei nebenbei zu flicken; das Übrige steht wie zuvor.'),
 q('报警犹有迟滞，所幸无事；烽备则日颓。', '報警猶有遲滯，所幸無事；烽備則日頹。', 'Alarms still lag, luckily with no harm — yet each day the beacon network decays.', 'Тревоги запаздывают, к счастью без беды; но каждый день сеть маяков гниёт.', '警報はなお遅れ、幸い禍はない——しかし烽火の備えは日に日に荒れる。', 'Alarme hinken noch, zum Glück ohne Schaden; doch Tag für Tag verfällt das Zeichennetz.')
)
ev('army_fund_embezzle', 2,
 ('军费中饱', '軍費中飽', 'The Embezzled Fund', 'Присвоенный фонд', '軍費の横領', 'Der veruntreute Fonds'),
 ('发往前线之饷银，转运官私吞三成，事为人揭发。{king}须处断。', '發往前線之餉銀，轉運官私吞三成，事為人揭發。{king}須處斷。', 'Of the wages bound for the front, a transport official swallowed three parts; the matter is revealed. {king} must hand down a judgment.', 'Из жалования, идущего на фронт, транспортный чиновник проглотил три части; дело раскрыто. {king} должен вынести приговор.', '前線へ送る給銀の三割を運送の官が私服した——事は露見した。{king}は裁断を下さねばならぬ。', 'Von dem Sold für die Front verschluckte ein Trossbeamter drei Teile; die Sache ist aufgedeckt. {king} muss ein Urteil sprechen.'),
 q('严办主事', '嚴辦主事', 'Try the case hard', 'Судить строго', '厳正に裁く', 'Streng richten'),
 q('拿问主事，籍没赃银，以肃纲纪。', '拿問主事，籍沒贓銀，以肅綱紀。', 'Arrest the officer, confiscate the purloined silver, and tighten the rules.', 'Арестовать чиновника, конфисковать украденное серебро и затянуть правила.', '主任を捕らえ賄銀を没収し、綱紀を引き締める。', 'Den Beamten festsetzen, das gestohlene Silber einziehen, die Regeln anziehen.'),
 q('贪吏伏法，而转运诸司人人自危，梗阻四起。', '貪吏伏法，而轉運諸司人人自危，梗阻四起。', 'The thief answers to the law, yet every transport office quakes for itself and blockages rise on all sides.', 'Вор отвечает перед законом, но каждый транспортный приказ дрожит за себя, и препятствия встают со всех сторон.', '貪吏は法に処され、運送の諸司は皆自分が危ういと震え、支障が四方に持ち上がる。', 'Der Dieb büßt vor dem Gesetz, doch jedes Transportamt bebt um sich selbst, und Hindernisse türmen sich von allen Seiten.'),
 q('追认补饷', '追認補餉', 'Make it good', 'Возместить', '庫で穴埋めする', 'Ausgleichen'),
 q('以库帑补足所吞之饷，各营暂安。', '以庫帑補足所吞之餉，各營暫安。', 'Refill the swallowed wages from the treasury; each camp is set at ease.', 'Пополнить проглоченное жалование из казны; каждый лагерь успокоен.', '呑まれた給銀を国庫から補えば、各営はしばし安らぐ。', 'Den verschluckten Sold aus der Kasse auffüllen; jedes Lager ist beruhigt.'),
 q('饷银补足，军心稍平；金库则再亏一笔。', '餉銀補足，軍心稍平；金庫則再虧一筆。', 'Wages are made whole and hearts ease a little, while the treasury loses a further sum.', 'Жалование цело, сердца чуть легче; казна теряет ещё одну сумму.', '給銀は満額になり軍心は凪ぐ——国庫はさらに一筆を失った。', 'Der Sold ist ganz, die Herzen leichten sich; die Kasse verliert eine weitere Summe.')
)
